In [9]:
import pandas as pd
import numpy as np
import requests
import json
import os
from config import username, api_key
from city_list import slist, clist, alist

Load up our BPD data for cleaning

In [10]:
city_path = os.path.join("Data","bpd_data.csv")
df = pd.read_csv(city_path)
df

,City,mean site eui,mean number of people,mean operating hours,mean occupant density,mean floor area,mean source eui
0,Birmingham,143.647642,356.923077,68.808462,2.025053,115640.11860,400.595034
1,Mobile,107.084978,NaN,NaN,NaN,70016.91400,315.907443
2,Montgomery,112.048215,NaN,NaN,NaN,82585.24382,298.702917
3,Huntsville,116.235841,NaN,NaN,NaN,37496.98899,362.019120
4,Tuscaloosa,189.021112,NaN,NaN,NaN,119205.34950,514.514461
5,Anchorage,133.111653,NaN,NaN,NaN,113163.47000,270.506011
6,Fairbanks,NaN,NaN,NaN,NaN,NaN,NaN
7,Juneau,89.367785,NaN,NaN,NaN,126827.53200,169.524359
8,Palmer,116.003042,NaN,NaN,NaN,26812.92857,158.043371
9,Wasilla,NaN,NaN,NaN,NaN,NaN,NaN
10,Phoenix,66.839636,247.945122,66.161159,2.417184,141551.86310,200.353735
11,Mesa,90.427591,127.700000,99.154000,1.635223,65555.67094,278.819932
12,Tucson,111.380086,105.714286,105.190893,1.322175,77062.20621,331.288908
13,Glendale,75.822699,424.000000,80.197111,2.010290,159690.97920,219.851930
14,Yuma,89.963936,NaN,NaN,NaN,56023.51324,275.588443
15,Little Rock,124.150876,403.272727,107.318182,2.269219,113052.33620,334.467534
16,Fayetteville,136.078645,NaN,NaN,NaN,66337.03022,364.645346
17,Fort Smith,113.799440,NaN,NaN,NaN,94551.48360,282.491408
18,Jonesboro,128.053377,NaN,NaN,NaN,65864.72222,358.951702
19,Conway,113.451620,NaN,NaN,NaN,67215.83333,312.372626
20,Los Angeles,81.087951,1019.349057,63.419112,2.631776,348019.74240,220.286297
21,San Francisco,64.640986,926.949045,67.745936,2.656458,161101.55480,158.428255
22,San Diego,60.451393,361.581967,62.641382,2.627188,89564.36571,145.160327
23,Irvine,62.142030,465.813333,56.345761,2.595104,137933.81600,168.017955
24,San Jose,81.370193,384.400000,67.045390,2.599932,105589.15790,222.419115
25,Denver,96.393579,638.220000,66.386765,2.398287,167341.56700,222.062377
26,Aurora,101.436132,176.259259,80.208889,1.639689,86601.80996,251.943943
27,Colorado Springs,109.031245,479.000000,81.554545,2.620595,94735.16111,263.506472
28,Fort Collins,65.148913,NaN,NaN,NaN,90923.75828,130.824530
29,Pueblo,133.108033,NaN,NaN,NaN,55546.18182,356.421142
...,...,...,...,...,...,...,...
208,Ogden,149.525761,NaN,NaN,NaN,90514.61217,346.195750
209,St. George,NaN,NaN,NaN,NaN,NaN,NaN
210,Logan,138.058773,NaN,NaN,NaN,86175.71429,299.186121
211,Burlington,92.676069,165.400000,71.695500,1.572702,100636.31900,249.731546
212,Montpelier,NaN,NaN,NaN,NaN,22350.57222,NaN
213,Virginia Beach,69.980373,144.181818,92.608182,2.377143,93877.97645,195.849460
214,Norfolk,96.194558,621.600000,69.898000,2.822722,139467.56570,270.941833
215,Richmond,112.704521,324.184211,76.794727,2.294704,124285.72170,315.214114
216,Hampton,97.878375,NaN,NaN,NaN,47657.25798,271.507662
217,Roanoke,84.184330,NaN,NaN,NaN,83955.17566,201.626666
218,Seattle,79.723243,942.616438,63.361812,2.543029,120734.85300,195.353594
219,Tacoma,129.815255,NaN,NaN,NaN,138851.04780,364.745391
220,Vancouver,93.065338,NaN,NaN,NaN,77988.87963,246.031284
221,Everett,135.191433,275.600000,64.521500,2.178689,99452.87805,344.729678
222,Spokane,134.096878,224.578947,75.030000,1.581039,83641.22991,334.870437
223,Charleston,124.496181,NaN,NaN,NaN,92774.34408,341.583570
224,Huntington,111.211455,NaN,NaN,NaN,47066.77660,256.794242
225,Parkersburg,NaN,NaN,NaN,NaN,NaN,NaN
226,Morgantown,117.756677,NaN,NaN,NaN,48879.10000,267.351905
227,Wheeling,97.567017,NaN,NaN,NaN,58477.24077,240.380868
228,Milwaukee,112.403837,481.125000,85.912092,1.921060,111891.42070,248.796168
229,Madison,125.285525,195.533333,87.102283,1.619649,104573.19110,303.706252
230,Waukesha,114.124402,NaN,NaN,NaN,68200.95241,281.617128
231,Green Bay,92.159108,NaN,NaN,NaN,110269.06120,222.376025
232,Appleton,89.422308,NaN,NaN,NaN,112723.45160,204.605858
233,Cheyenne,111.067800,NaN,NaN,NaN,129977.90580,258.143498
234,Casper,118.813999,NaN,NaN,NaN,66967.90238,296.798243
235,Gillette,110.658160,NaN,NaN,NaN,43648.37500,268.584859
236,Laramie,79.391602,NaN,NaN,NaN,39724.10000,179.518493
237,Riverton,130.309810,NaN,NaN,NaN,59840.21111,297.670463

Add this list so we can combine the BPD Data with climate data AKA merge on this field

In [11]:
df["state"]=alist
df["name"]=df["City"]+", "+df["state"]+" US"
df

,City,mean site eui,mean number of people,mean operating hours,mean occupant density,mean floor area,mean source eui,state,name
0,Birmingham,143.647642,356.923077,68.808462,2.025053,115640.11860,400.595034,AL,"Birmingham, AL US"
1,Mobile,107.084978,NaN,NaN,NaN,70016.91400,315.907443,AL,"Mobile, AL US"
2,Montgomery,112.048215,NaN,NaN,NaN,82585.24382,298.702917,AL,"Montgomery, AL US"
3,Huntsville,116.235841,NaN,NaN,NaN,37496.98899,362.019120,AL,"Huntsville, AL US"
4,Tuscaloosa,189.021112,NaN,NaN,NaN,119205.34950,514.514461,AL,"Tuscaloosa, AL US"
5,Anchorage,133.111653,NaN,NaN,NaN,113163.47000,270.506011,AK,"Anchorage, AK US"
6,Fairbanks,NaN,NaN,NaN,NaN,NaN,NaN,AK,"Fairbanks, AK US"
7,Juneau,89.367785,NaN,NaN,NaN,126827.53200,169.524359,AK,"Juneau, AK US"
8,Palmer,116.003042,NaN,NaN,NaN,26812.92857,158.043371,AK,"Palmer, AK US"
9,Wasilla,NaN,NaN,NaN,NaN,NaN,NaN,AK,"Wasilla, AK US"
10,Phoenix,66.839636,247.945122,66.161159,2.417184,141551.86310,200.353735,AZ,"Phoenix, AZ US"
11,Mesa,90.427591,127.700000,99.154000,1.635223,65555.67094,278.819932,AZ,"Mesa, AZ US"
12,Tucson,111.380086,105.714286,105.190893,1.322175,77062.20621,331.288908,AZ,"Tucson, AZ US"
13,Glendale,75.822699,424.000000,80.197111,2.010290,159690.97920,219.851930,AZ,"Glendale, AZ US"
14,Yuma,89.963936,NaN,NaN,NaN,56023.51324,275.588443,AZ,"Yuma, AZ US"
15,Little Rock,124.150876,403.272727,107.318182,2.269219,113052.33620,334.467534,AR,"Little Rock, AR US"
16,Fayetteville,136.078645,NaN,NaN,NaN,66337.03022,364.645346,AR,"Fayetteville, AR US"
17,Fort Smith,113.799440,NaN,NaN,NaN,94551.48360,282.491408,AR,"Fort Smith, AR US"
18,Jonesboro,128.053377,NaN,NaN,NaN,65864.72222,358.951702,AR,"Jonesboro, AR US"
19,Conway,113.451620,NaN,NaN,NaN,67215.83333,312.372626,AR,"Conway, AR US"
20,Los Angeles,81.087951,1019.349057,63.419112,2.631776,348019.74240,220.286297,CA,"Los Angeles, CA US"
21,San Francisco,64.640986,926.949045,67.745936,2.656458,161101.55480,158.428255,CA,"San Francisco, CA US"
22,San Diego,60.451393,361.581967,62.641382,2.627188,89564.36571,145.160327,CA,"San Diego, CA US"
23,Irvine,62.142030,465.813333,56.345761,2.595104,137933.81600,168.017955,CA,"Irvine, CA US"
24,San Jose,81.370193,384.400000,67.045390,2.599932,105589.15790,222.419115,CA,"San Jose, CA US"
25,Denver,96.393579,638.220000,66.386765,2.398287,167341.56700,222.062377,CO,"Denver, CO US"
26,Aurora,101.436132,176.259259,80.208889,1.639689,86601.80996,251.943943,CO,"Aurora, CO US"
27,Colorado Springs,109.031245,479.000000,81.554545,2.620595,94735.16111,263.506472,CO,"Colorado Springs, CO US"
28,Fort Collins,65.148913,NaN,NaN,NaN,90923.75828,130.824530,CO,"Fort Collins, CO US"
29,Pueblo,133.108033,NaN,NaN,NaN,55546.18182,356.421142,CO,"Pueblo, CO US"
...,...,...,...,...,...,...,...,...,...
208,Ogden,149.525761,NaN,NaN,NaN,90514.61217,346.195750,UT,"Ogden, UT US"
209,St. George,NaN,NaN,NaN,NaN,NaN,NaN,UT,"St. George, UT US"
210,Logan,138.058773,NaN,NaN,NaN,86175.71429,299.186121,UT,"Logan, UT US"
211,Burlington,92.676069,165.400000,71.695500,1.572702,100636.31900,249.731546,VT,"Burlington, VT US"
212,Montpelier,NaN,NaN,NaN,NaN,22350.57222,NaN,VT,"Montpelier, VT US"
213,Virginia Beach,69.980373,144.181818,92.608182,2.377143,93877.97645,195.849460,VA,"Virginia Beach, VA US"
214,Norfolk,96.194558,621.600000,69.898000,2.822722,139467.56570,270.941833,VA,"Norfolk, VA US"
215,Richmond,112.704521,324.184211,76.794727,2.294704,124285.72170,315.214114,VA,"Richmond, VA US"
216,Hampton,97.878375,NaN,NaN,NaN,47657.25798,271.507662,VA,"Hampton, VA US"
217,Roanoke,84.184330,NaN,NaN,NaN,83955.17566,201.626666,VA,"Roanoke, VA US"
218,Seattle,79.723243,942.616438,63.361812,2.543029,120734.85300,195.353594,WA,"Seattle, WA US"
219,Tacoma,129.815255,NaN,NaN,NaN,138851.04780,364.745391,WA,"Tacoma, WA US"
220,Vancouver,93.065338,NaN,NaN,NaN,77988.87963,246.031284,WA,"Vancouver, WA US"
221,Everett,135.191433,275.600000,64.521500,2.178689,99452.87805,344.729678,WA,"Everett, WA US"
222,Spokane,134.096878,224.578947,75.030000,1.581039,83641.22991,334.870437,WA,"Spokane, WA US"
223,Charleston,124.496181,NaN,NaN,NaN,92774.34408,341.583570,WV,"Charleston, WV US"
224,Huntington,111.211455,NaN,NaN,NaN,47066.77660,256.794242,WV,"Huntington, WV US"
225,Parkersburg,NaN,NaN,NaN,NaN,NaN,NaN,WV,"Parkersburg, WV US"
226,Morgantown,117.756677,NaN,NaN,NaN,48879.10000,267.351905,WV,"Morgantown, WV US"
227,Wheeling,97.567017,NaN,NaN,NaN,58477.24077,240.380868,WV,"Wheeling, WV US"
228,Milwaukee,112.403837,481.125000,85.912092,1.921060,111891.42070,248.796168,WI,"Milwaukee, WI US"
229,Madison,125.285525,195.533333,87.102283,1.619649,104573.19110,303.706252,WI,"Madison, WI US"
230,Waukesha,114.124402,NaN,NaN,NaN,68200.95241,281.617128,WI,"Waukesha, WI US"
231,Green Bay,92.159108,NaN,NaN,NaN,110269.06120,222.376025,WI,"Green Bay, WI US"
232,Appleton,89.422308,NaN,NaN,NaN,112723.45160,204.605858,WI,"Appleton, WI US"
233,Cheyenne,111.067800,NaN,NaN,NaN,129977.90580,258.143498,WY,"Cheyenne, WY US"
234,Casper,118.813999,NaN,NaN,NaN,66967.90238,296.798243,WY,"Casper, WY US"
235,Gillette,110.658160,NaN,NaN,NaN,43648.37500,268.584859,WY,"Gillette, WY US"
236,Laramie,79.391602,NaN,NaN,NaN,39724.10000,179.518493,WY,"Laramie, WY US"
237,Riverton,130.309810,NaN,NaN,NaN,59840.21111,297.670463,WY,"Riverton, WY US"

Grab the weather data

In [12]:
weather_path = os.path.join("Data","weather_data.csv")
df2 = pd.read_csv(weather_path)
df2 = df2.drop("id",axis=1)
#df2.rename({"name":lookup})
df2

,name,CDD,HDD,Tavg,Trange,Tmax,Tmin,Prcp,Snow
0,"Birmingham, AL US",1933,2770,62.78,22.46,73.94,51.44,5712,8
1,"Huntsville, AL US",1540,3517,59.54,23.90,71.42,47.66,5582,24
2,"Mobile, AL US",2537,1656,67.46,18.68,76.64,58.10,6528,2
3,"Montgomery, AL US",2113,2278,64.58,23.54,76.28,52.88,5280,0
4,"Tuscaloosa, AL US",2348,2338,64.94,22.64,76.28,53.78,5046,2
5,"Anchorage, AK US",3,10201,37.04,14.00,44.06,30.02,1667,821
6,"Fairbanks, AK US",41,13504,28.04,21.02,38.66,17.60,1218,644
7,"Juneau, AK US",-7777,9302,39.56,10.94,44.96,33.98,11687,823
8,"Mesa, AZ US",3592,1462,70.88,27.68,84.56,57.02,943,0
9,"Phoenix, AZ US",3741,1359,71.42,34.34,88.70,54.32,876,0
10,"Tucson, AZ US",1946,2486,63.50,37.22,82.04,44.96,1390,23
11,"Yuma, AZ US",3811,1129,72.32,29.84,87.26,57.38,368,0
12,"Conway, AR US",1843,3472,60.44,22.82,71.96,49.10,4908,41
13,"Fayetteville, AR US",1517,4013,58.28,20.84,68.54,47.66,4553,43
14,"Fort Smith, AR US",2053,3244,61.70,22.28,72.86,50.54,5041,46
15,"Jonesboro, AR US",1735,3846,59.18,21.92,70.16,48.20,4823,48
16,"Little Rock, AR US",2170,3006,62.78,18.68,71.96,53.24,5468,44
17,"Los Angeles, CA US",1638,880,67.10,22.64,78.44,55.76,2297,0
18,"San Diego, CA US",1241,1909,63.14,21.92,74.12,52.16,1677,1
19,"San Francisco, CA US",174,2701,58.10,19.40,67.82,48.38,2674,0
20,"San Jose, CA US",395,2735,58.64,30.20,73.76,43.52,5048,1
21,"Colorado Springs, CO US",6,9474,39.02,27.32,52.88,25.34,1882,249
22,"Denver, CO US",15,8879,40.64,31.64,56.66,24.80,1773,857
23,"Fort Collins, CO US",250,7381,45.32,22.64,56.66,34.16,2162,1661
24,"Pueblo, CO US",1092,5195,53.78,30.56,69.08,38.48,1302,193
25,"Bridgeport, CT US",745,5650,51.44,18.86,60.98,42.08,5110,276
26,"Hartford, CT US",603,6318,49.28,21.92,60.26,38.48,5344,313
27,"New Haven, CT US",745,5650,51.44,18.86,60.98,42.08,5110,310
28,"Stamford, CT US",799,5443,52.34,21.92,63.14,41.36,5004,312
29,"Waterbury, CT US",754,5678,51.44,20.84,61.88,41.00,5110,310
...,...,...,...,...,...,...,...,...,...
178,"San Antonio, TX US",2364,2049,65.84,24.80,78.26,53.42,3810,-7777
179,"Logan, UT US",704,6680,48.56,21.74,59.54,37.76,1776,415
180,"Ogden, UT US",1174,5670,52.70,17.24,61.34,44.06,1338,485
181,"Provo, UT US",662,5962,50.54,24.62,62.78,38.12,2053,698
182,"Salt Lake City, UT US",21,9639,38.66,18.32,47.84,29.48,5423,5461
183,"St. George, UT US",2604,2986,63.86,25.88,76.82,51.08,1319,41
184,"Burlington, VT US",484,7432,45.86,18.68,55.22,36.68,3104,852
185,"Montpelier, VT US",453,7983,44.42,24.62,56.66,32.00,4242,805
186,"Hampton, VA US",1836,2958,61.88,17.06,70.34,53.42,5079,49
187,"Norfolk, VA US",1836,2958,61.88,17.06,70.34,53.42,5079,49
188,"Richmond, VA US",1292,4096,57.38,20.66,67.64,46.94,4341,165
189,"Roanoke, VA US",1061,4354,55.94,23.54,67.64,44.24,4711,213
190,"Virginia Beach, VA US",1647,3215,60.62,16.52,69.08,52.34,5079,58
191,"Everett, WA US",111,4937,51.80,17.78,60.62,42.98,3844,25
192,"Seattle, WA US",165,4919,51.98,16.88,60.44,43.52,5637,35
193,"Spokane, WA US",249,7139,46.04,21.74,57.02,35.24,1708,541
194,"Tacoma, WA US",223,4531,53.24,17.24,61.88,44.60,3914,48
195,"Vancouver, WA US",330,4447,53.78,21.20,64.22,43.16,4058,28
196,"Charleston, WV US",924,4955,53.96,23.36,65.66,42.26,4622,264
197,"Huntington, WV US",948,5223,53.24,21.38,63.86,42.62,4413,68
198,"Morgantown, WV US",744,5709,51.44,22.46,62.60,40.28,3958,378
199,"Parkersburg, WV US",894,5229,53.06,21.74,64.04,42.26,4106,119
200,"Wheeling, WV US",909,5303,53.06,21.74,63.86,42.08,4256,171
201,"Green Bay, WI US",358,7885,44.42,18.50,53.60,35.06,3127,514
202,"Madison, WI US",597,7283,46.76,21.38,57.38,35.96,3727,379
203,"Milwaukee, WI US",568,7304,46.58,18.50,55.76,37.22,3450,359
204,"Casper, WY US",314,7866,44.24,25.88,57.20,31.46,1301,734
205,"Cheyenne, WY US",364,7170,46.22,30.92,61.88,30.92,1727,512
206,"Gillette, WY US",522,7375,46.22,26.06,59.18,33.26,1694,588
207,"Laramie, WY US",70,8767,41.18,29.12,55.76,26.60,1143,497

Load up the residential data

In [13]:
res_path = os.path.join("Data","bpd_data_residential.csv")
dfres = pd.read_csv(res_path)
dfres["City"] = df["name"]
dfres = dfres.rename(columns={"City":"name",
                             "mean source eui":"mean source eui res",
                             "mean site eui":"mean site eui res"})
dfres

                        name  mean source eui res  mean site eui res
0          Birmingham, AL US            96.557022          50.020103
1              Mobile, AL US           117.940363          50.998702
2          Montgomery, AL US                  NaN                NaN
3          Huntsville, AL US                  NaN                NaN
4          Tuscaloosa, AL US                  NaN                NaN
5           Anchorage, AK US            86.474614          55.616592
6           Fairbanks, AK US                  NaN                NaN
7              Juneau, AK US                  NaN                NaN
8              Palmer, AK US                  NaN                NaN
9             Wasilla, AK US                  NaN                NaN
10            Phoenix, AZ US            95.292175          34.146045
11               Mesa, AZ US            95.648604          30.461339
12             Tucson, AZ US            84.472751          32.412979
13           Glendale, AZ US                  NaN                NaN
14               Yuma, AZ US           129.802519          43.328682
15        Little Rock, AR US           139.299537          61.015530
16       Fayetteville, AR US            88.438439          35.155192
17         Fort Smith, AR US                  NaN                NaN
18          Jonesboro, AR US                  NaN                NaN
19             Conway, AR US           122.396399          38.979745
20        Los Angeles, CA US            54.786719          27.359427
21      San Francisco, CA US            64.415370          40.110887
22          San Diego, CA US            62.232609          32.116250
23             Irvine, CA US            44.562117          22.837398
24           San Jose, CA US            63.062242          34.099588
25             Denver, CO US            98.117881          41.870882
26             Aurora, CO US            67.997506          39.035943
27   Colorado Springs, CO US           106.583514          63.695016
28       Fort Collins, CO US            89.902512          36.452121
29             Pueblo, CO US                  NaN                NaN
..                       ...                  ...                ...
208             Ogden, UT US            84.463432          50.792128
209        St. George, UT US                  NaN                NaN
210             Logan, UT US                  NaN                NaN
211        Burlington, VT US                  NaN                NaN
212        Montpelier, VT US                  NaN                NaN
213    Virginia Beach, VA US           121.341974          58.197400
214           Norfolk, VA US                  NaN                NaN
215          Richmond, VA US           103.406177          43.936039
216           Hampton, VA US            99.753041          38.027843
217           Roanoke, VA US                  NaN                NaN
218           Seattle, WA US            90.929735          36.055703
219            Tacoma, WA US                  NaN                NaN
220         Vancouver, WA US                  NaN                NaN
221           Everett, WA US                  NaN                NaN
222           Spokane, WA US                  NaN                NaN
223        Charleston, WV US           132.482015          49.873167
224        Huntington, WV US                  NaN                NaN
225       Parkersburg, WV US                  NaN                NaN
226        Morgantown, WV US                  NaN                NaN
227          Wheeling, WV US                  NaN                NaN
228         Milwaukee, WI US            93.838426          61.219314
229           Madison, WI US            86.489930          55.601269
230          Waukesha, WI US                  NaN                NaN
231         Green Bay, WI US            47.659936          22.648930
232          Appleton, WI US                  NaN                NaN
233          Cheyenne, WY US                  NaN                NaN
234            Casper, WY US                  NaN                NaN
235          Gillette, WY US                  NaN                NaN
236           Laramie, WY US                  NaN                NaN
237          Riverton, WY US                  NaN                NaN

[238 rows x 3 columns]

Load up the additional data for further analysis

In [14]:
ad_path = os.path.join("Data","bpd_data_additional.csv")
dfad = pd.read_csv(ad_path)
dfad = dfad.rename(columns={"city":"City"})
dfad

,City,mean electirc eui,mean electric eui res,mean fuel eui,mean fuel eui res
0,Birmingham,143.311563,21.116271,25.618049,NaN
1,Mobile,120.403278,30.169515,10.227344,NaN
2,Montgomery,104.782978,NaN,24.801954,NaN
3,Huntsville,140.163935,27.781260,32.382384,NaN
4,Tuscaloosa,160.009627,NaN,36.074106,NaN
5,Anchorage,90.755170,13.434063,66.884246,NaN
6,Juneau,33.031979,NaN,NaN,NaN
7,Phoenix,76.588709,26.895603,4.228576,5.881798
8,Mesa,123.888037,30.461339,2.630878,0.000000
9,Tucson,119.370537,24.753733,8.777518,9.298245
10,Yuma,139.602654,40.368228,2.726742,3.322212
11,Little Rock,110.742169,36.937149,26.681641,25.018769
12,Fayetteville,115.174324,23.263998,31.320575,11.478266
13,Fort Smith,79.046639,NaN,37.946755,NaN
14,Jonesboro,110.097287,NaN,21.670569,NaN
15,Conway,94.732085,38.123944,22.037656,0.037681
16,Los Angeles,87.060861,12.482543,16.832243,14.489057
17,San Francisco,62.009912,11.273363,16.371552,31.042033
18,San Diego,52.791774,13.641363,21.450765,18.474799
19,San Jose,79.824916,12.882705,15.928660,20.914838
20,Denver,60.529204,25.952758,39.046700,15.919006
21,Colorado Springs,73.671774,19.055994,37.605513,43.550232
22,Fort Collins,29.391001,24.702289,33.549288,11.749832
23,Pueblo,114.613892,NaN,29.821025,NaN
24,New Haven,78.071187,14.722778,46.605382,22.938729
25,Bridgeport,89.636319,14.650037,51.325919,NaN
26,Hartford,43.771088,13.409215,34.538848,23.319241
27,Stamford,74.374634,NaN,18.012045,NaN
28,Waterbury,115.041061,13.934902,29.454678,NaN
29,Dover,62.785287,19.470050,41.378846,26.942772
...,...,...,...,...,...
163,Houston,80.580466,28.982608,12.989201,27.245043
164,Dallas,85.168085,36.714383,7.799117,19.415924
165,San Antonio,105.178000,27.310792,7.970949,12.584208
166,Austin,85.444340,NaN,8.992273,NaN
167,Salt Lake City,82.400703,17.200833,52.629191,48.475668
168,Provo,NaN,NaN,NaN,NaN
169,Ogden,97.167726,15.695421,62.420204,35.896579
170,Logan,73.889033,NaN,64.113704,NaN
171,Burlington,77.804001,NaN,19.151181,NaN
172,Virginia Beach,62.971897,27.777557,11.411926,29.376968
173,Norfolk,86.462865,NaN,13.355791,NaN
174,Richmond,100.204312,19.247214,18.722155,16.625876
175,Hampton,86.789857,28.686374,19.020005,10.249316
176,Roanoke,55.884772,NaN,30.615587,NaN
177,Seattle,95.486408,25.535467,26.399558,25.045394
178,Tacoma,141.280182,NaN,21.408599,NaN
179,Vancouver,72.812822,NaN,21.298654,NaN
180,Everett,105.176329,NaN,37.774922,NaN
181,Spokane,94.665363,NaN,40.508535,NaN
182,Charleston,119.992456,NaN,21.209472,NaN
183,Huntington,75.172442,8.694155,41.882126,NaN
184,Morgantown,68.456991,NaN,17.273913,NaN
185,Wheeling,61.077689,NaN,32.459815,NaN
186,Milwaukee,63.276562,14.606104,50.805827,48.327908
187,Madison,86.972623,13.684957,43.368531,42.304402
188,Green Bay,59.517960,10.534924,30.730914,23.629515
189,Cheyenne,70.353458,NaN,41.147110,NaN
190,Casper,81.751226,NaN,32.854181,NaN
191,Gillette,68.486712,NaN,35.230860,NaN
192,Laramie,NaN,29.856481,NaN,NaN

Merge!!

In [17]:
df3 = pd.merge(df, df2, on="name",how="inner")
df3 = pd.merge(df3, dfres, on="name",how="inner")
df3 = pd.merge(df3, dfad, on="City",how="inner")
df3 = df3.drop("name",axis=1)
df3 = df3.rename(columns={"mean electirc eui":"mean electric eui"})
df3

,City,mean site eui,mean number of people,mean operating hours,mean occupant density,mean floor area,mean source eui,state,CDD,HDD,...,Tmax,Tmin,Prcp,Snow,mean source eui res,mean site eui res,mean electric eui,mean electric eui res,mean fuel eui,mean fuel eui res
0,Birmingham,143.647642,356.923077,68.808462,2.025053,115640.11860,400.595034,AL,1933,2770,...,73.94,51.44,5712,8,96.557022,50.020103,143.311563,21.116271,25.618049,NaN
1,Mobile,107.084978,NaN,NaN,NaN,70016.91400,315.907443,AL,2537,1656,...,76.64,58.10,6528,2,117.940363,50.998702,120.403278,30.169515,10.227344,NaN
2,Montgomery,112.048215,NaN,NaN,NaN,82585.24382,298.702917,AL,2113,2278,...,76.28,52.88,5280,0,NaN,NaN,104.782978,NaN,24.801954,NaN
3,Huntsville,116.235841,NaN,NaN,NaN,37496.98899,362.019120,AL,1540,3517,...,71.42,47.66,5582,24,NaN,NaN,140.163935,27.781260,32.382384,NaN
4,Tuscaloosa,189.021112,NaN,NaN,NaN,119205.34950,514.514461,AL,2348,2338,...,76.28,53.78,5046,2,NaN,NaN,160.009627,NaN,36.074106,NaN
5,Anchorage,133.111653,NaN,NaN,NaN,113163.47000,270.506011,AK,3,10201,...,44.06,30.02,1667,821,86.474614,55.616592,90.755170,13.434063,66.884246,NaN
6,Juneau,89.367785,NaN,NaN,NaN,126827.53200,169.524359,AK,-7777,9302,...,44.96,33.98,11687,823,NaN,NaN,33.031979,NaN,NaN,NaN
7,Phoenix,66.839636,247.945122,66.161159,2.417184,141551.86310,200.353735,AZ,3741,1359,...,88.70,54.32,876,0,95.292175,34.146045,76.588709,26.895603,4.228576,5.881798
8,Mesa,90.427591,127.700000,99.154000,1.635223,65555.67094,278.819932,AZ,3592,1462,...,84.56,57.02,943,0,95.648604,30.461339,123.888037,30.461339,2.630878,0.000000
9,Tucson,111.380086,105.714286,105.190893,1.322175,77062.20621,331.288908,AZ,1946,2486,...,82.04,44.96,1390,23,84.472751,32.412979,119.370537,24.753733,8.777518,9.298245
10,Yuma,89.963936,NaN,NaN,NaN,56023.51324,275.588443,AZ,3811,1129,...,87.26,57.38,368,0,129.802519,43.328682,139.602654,40.368228,2.726742,3.322212
11,Little Rock,124.150876,403.272727,107.318182,2.269219,113052.33620,334.467534,AR,2170,3006,...,71.96,53.24,5468,44,139.299537,61.015530,110.742169,36.937149,26.681641,25.018769
12,Fayetteville,136.078645,NaN,NaN,NaN,66337.03022,364.645346,AR,1517,4013,...,68.54,47.66,4553,43,88.438439,35.155192,115.174324,23.263998,31.320575,11.478266
13,Fort Smith,113.799440,NaN,NaN,NaN,94551.48360,282.491408,AR,2053,3244,...,72.86,50.54,5041,46,NaN,NaN,79.046639,NaN,37.946755,NaN
14,Jonesboro,128.053377,NaN,NaN,NaN,65864.72222,358.951702,AR,1735,3846,...,70.16,48.20,4823,48,NaN,NaN,110.097287,NaN,21.670569,NaN
15,Conway,113.451620,NaN,NaN,NaN,67215.83333,312.372626,AR,1843,3472,...,71.96,49.10,4908,41,122.396399,38.979745,94.732085,38.123944,22.037656,0.037681
16,Los Angeles,81.087951,1019.349057,63.419112,2.631776,348019.74240,220.286297,CA,1638,880,...,78.44,55.76,2297,0,54.786719,27.359427,87.060861,12.482543,16.832243,14.489057
17,San Francisco,64.640986,926.949045,67.745936,2.656458,161101.55480,158.428255,CA,174,2701,...,67.82,48.38,2674,0,64.415370,40.110887,62.009912,11.273363,16.371552,31.042033
18,San Diego,60.451393,361.581967,62.641382,2.627188,89564.36571,145.160327,CA,1241,1909,...,74.12,52.16,1677,1,62.232609,32.116250,52.791774,13.641363,21.450765,18.474799
19,San Jose,81.370193,384.400000,67.045390,2.599932,105589.15790,222.419115,CA,395,2735,...,73.76,43.52,5048,1,63.062242,34.099588,79.824916,12.882705,15.928660,20.914838
20,Denver,96.393579,638.220000,66.386765,2.398287,167341.56700,222.062377,CO,15,8879,...,56.66,24.80,1773,857,98.117881,41.870882,60.529204,25.952758,39.046700,15.919006
21,Colorado Springs,109.031245,479.000000,81.554545,2.620595,94735.16111,263.506472,CO,6,9474,...,52.88,25.34,1882,249,106.583514,63.695016,73.671774,19.055994,37.605513,43.550232
22,Fort Collins,65.148913,NaN,NaN,NaN,90923.75828,130.824530,CO,250,7381,...,56.66,34.16,2162,1661,89.902512,36.452121,29.391001,24.702289,33.549288,11.749832
23,Pueblo,133.108033,NaN,NaN,NaN,55546.18182,356.421142,CO,1092,5195,...,69.08,38.48,1302,193,NaN,NaN,114.613892,NaN,29.821025,NaN
24,New Haven,119.555818,NaN,NaN,NaN,121945.82800,279.320079,CT,745,5650,...,60.98,42.08,5110,310,91.052447,44.265730,78.071187,14.722778,46.605382,22.938729
25,Bridgeport,130.564214,NaN,NaN,NaN,93602.24429,309.549060,CT,745,5650,...,60.98,42.08,5110,276,NaN,NaN,89.636319,14.650037,51.325919,NaN
26,Hartford,78.551224,NaN,NaN,NaN,506629.58880,167.277800,CT,603,6318,...,60.26,38.48,5344,313,57.736001,29.069842,43.771088,13.409215,34.538848,23.319241
27,Stamford,93.642628,NaN,NaN,NaN,221193.16670,248.085028,CT,799,5443,...,63.14,41.36,5004,312,NaN,NaN,74.374634,NaN,18.012045,NaN
28,Waterbury,107.866691,NaN,NaN,NaN,38508.63333,274.893021,CT,754,5678,...,61.88,41.00,5110,310,NaN,NaN,115.041061,13.934902,29.454678,NaN
29,Dover,104.369062,186.384615,77.038462,1.261553,62634.18835,241.602734,DE,1314,4269,...,66.38,47.48,4605,157,87.177836,44.708310,62.785287,19.470050,41.378846,26.942772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,Chattanooga,96.622230,NaN,NaN,NaN,144639.64960,271.289067,TN,1433,3560,...,71.78,46.58,4499,0,99.875055,37.640865,92.403689,28.773300,17.415340,8.763063
178,Houston,82.477333,920.546296,62.202600,2.656543,289531.97290,231.724191,TX,2586,1469,...,77.18,58.82,5350,0,116.792327,55.328099,80.580466,28.982608,12.989201,27.245043
179,Dallas,88.021084,966.965517,62.014830,2.321133,359069.06280,260.472621,TX,2463,2429,...,77.00,53.06,4015,7,141.980934,58.128452,85.168085,36.714383,7.799117,19.415924
180,San Antonio,96.113849,667.442308,77.472436,2.379787,204352.99690,284.631208,TX,2364,2049,...,78.26,53.42,3810,-7777,103.623493,41.376379,105.178000,27.310792,7.970949,12.584208
181,Austin,83.457189,555.386667,75.252952,3.623255,162501.83900,242.526512,TX,2710,1918,...,79.16,55.04,3489,6,93.415740,42.981098,85.444340,NaN,8.992273,NaN
182,Salt Lake City,134.568281,346.040000,98.823590,2.387575,103532.86050,315.097126,UT,21,9639,...,47.84,29.48,5423,5461,107.489209,66.467716,82.400703,17.200833,52.629191,48.475668
183,Provo,93.406771,NaN,NaN,NaN,55211.04455,234.716828,UT,662,5962,...,62.78,38.12,2053,698,NaN,NaN,NaN,NaN,NaN,NaN
184,Ogden,149.525761,NaN,NaN,NaN,90514.61217,346.195750,UT,1174,5670,...,61.34,44.06,1338,485,84.463432,50.792128,97.167726,15.695421,62.420204,35.896579
185,Logan,138.058773,NaN,NaN,NaN,86175.71429,299.186121,UT,704,6680,...,59.54,37.76,1776,415,NaN,NaN,73.889033,NaN,64.113704,NaN
186,Burlington,92.676069,165.400000,71.695500,1.572702,100636.31900,249.731546,VT,484,7432,...,55.22,36.68,3104,852,NaN,NaN,77.804001,NaN,19.151181,NaN
187,Virginia Beach,69.980373,144.181818,92.608182,2.377143,93877.97645,195.849460,VA,1647,3215,...,69.08,52.34,5079,58,121.341974,58.197400,62.971897,27.777557,11.411926,29.376968
188,Norfolk,96.194558,621.600000,69.898000,2.822722,139467.56570,270.941833,VA,1836,2958,...,70.34,53.42,5079,49,NaN,NaN,86.462865,NaN,13.355791,NaN
189,Richmond,112.704521,324.184211,76.794727,2.294704,124285.72170,315.214114,VA,1292,4096,...,67.64,46.94,4341,165,103.406177,43.936039,100.204312,19.247214,18.722155,16.625876
190,Hampton,97.878375,NaN,NaN,NaN,47657.25798,271.507662,VA,1836,2958,...,70.34,53.42,5079,49,99.753041,38.027843,86.789857,28.686374,19.020005,10.249316
191,Roanoke,84.184330,NaN,NaN,NaN,83955.17566,201.626666,VA,1061,4354,...,67.64,44.24,4711,213,NaN,NaN,55.884772,NaN,30.615587,NaN
192,Seattle,79.723243,942.616438,63.361812,2.543029,120734.85300,195.353594,WA,165,4919,...,60.44,43.52,5637,35,90.929735,36.055703,95.486408,25.535467,26.399558,25.045394
193,Tacoma,129.815255,NaN,NaN,NaN,138851.04780,364.745391,WA,223,4531,...,61.88,44.60,3914,48,NaN,NaN,141.280182,NaN,21.408599,NaN
194,Vancouver,93.065338,NaN,NaN,NaN,77988.87963,246.031284,WA,330,4447,...,64.22,43.16,4058,28,NaN,NaN,72.812822,NaN,21.298654,NaN
195,Everett,135.191433,275.600000,64.521500,2.178689,99452.87805,344.729678,WA,111,4937,...,60.62,42.98,3844,25,NaN,NaN,105.176329,NaN,37.774922,NaN
196,Spokane,134.096878,224.578947,75.030000,1.581039,83641.22991,334.870437,WA,249,7139,...,57.02,35.24,1708,541,NaN,NaN,94.665363,NaN,40.508535,NaN
197,Huntington,111.211455,NaN,NaN,NaN,47066.77660,256.794242,WV,948,5223,...,63.86,42.62,4413,68,NaN,NaN,75.172442,8.694155,41.882126,NaN
198,Morgantown,117.756677,NaN,NaN,NaN,48879.10000,267.351905,WV,744,5709,...,62.60,40.28,3958,378,NaN,NaN,68.456991,NaN,17.273913,NaN
199,Wheeling,97.567017,NaN,NaN,NaN,58477.24077,240.380868,WV,909,5303,...,63.86,42.08,4256,171,NaN,NaN,61.077689,NaN,32.459815,NaN
200,Milwaukee,112.403837,481.125000,85.912092,1.921060,111891.42070,248.796168,WI,568,7304,...,55.76,37.22,3450,359,93.838426,61.219314,63.276562,14.606104,50.805827,48.327908
201,Madison,125.285525,195.533333,87.102283,1.619649,104573.19110,303.706252,WI,597,7283,...,57.38,35.96,3727,379,86.489930,55.601269,86.972623,13.684957,43.368531,42.304402
202,Green Bay,92.159108,NaN,NaN,NaN,110269.06120,222.376025,WI,358,7885,...,53.60,35.06,3127,514,47.659936,22.648930,59.517960,10.534924,30.730914,23.629515
203,Cheyenne,111.067800,NaN,NaN,NaN,129977.90580,258.143498,WY,364,7170,...,61.88,30.92,1727,512,NaN,NaN,70.353458,NaN,41.147110,NaN
204,Casper,118.813999,NaN,NaN,NaN,66967.90238,296.798243,WY,314,7866,...,57.20,31.46,1301,734,NaN,NaN,81.751226,NaN,32.854181,NaN
205,Gillette,110.658160,NaN,NaN,NaN,43648.37500,268.584859,WY,522,7375,...,59.18,33.26,1694,588,NaN,NaN,68.486712,NaN,35.230860,NaN
206,Laramie,79.391602,NaN,NaN,NaN,39724.10000,179.518493,WY,70,8767,...,55.76,26.60,1143,497,NaN,NaN,NaN,29.856481,NaN,NaN

Were going to take out some columns we don't need anymore and rearrage them

In [18]:
df4 = df3[['City', 'state', 'mean site eui', 'mean site eui res', 'mean source eui','mean source eui res', 'mean fuel eui','mean fuel eui res', 'mean electric eui','mean electric eui res', 'CDD', 'HDD', 'Tavg', 'Trange', 'Tmax', 'Tmin', 'Prcp', 'Snow']]
df4 = df4.rename(columns={"City":"city"})

Doing some cleaning, we can't make comparisons if the data in site eui doesn't exist
df5 is for commercial
df6 is for residential

In [20]:
df5 = df4.dropna(axis=0,subset=["mean site eui"])
df6 = df4.dropna(axis=0,subset=["mean site eui res"])
df5

,city,state,mean site eui,mean site eui res,mean source eui,mean source eui res,mean fuel eui,mean fuel eui res,mean electric eui,mean electric eui res,CDD,HDD,Tavg,Trange,Tmax,Tmin,Prcp,Snow
0,Birmingham,AL,143.647642,50.020103,400.595034,96.557022,25.618049,NaN,143.311563,21.116271,1933,2770,62.78,22.46,73.94,51.44,5712,8
1,Mobile,AL,107.084978,50.998702,315.907443,117.940363,10.227344,NaN,120.403278,30.169515,2537,1656,67.46,18.68,76.64,58.10,6528,2
2,Montgomery,AL,112.048215,NaN,298.702917,NaN,24.801954,NaN,104.782978,NaN,2113,2278,64.58,23.54,76.28,52.88,5280,0
3,Huntsville,AL,116.235841,NaN,362.019120,NaN,32.382384,NaN,140.163935,27.781260,1540,3517,59.54,23.90,71.42,47.66,5582,24
4,Tuscaloosa,AL,189.021112,NaN,514.514461,NaN,36.074106,NaN,160.009627,NaN,2348,2338,64.94,22.64,76.28,53.78,5046,2
5,Anchorage,AK,133.111653,55.616592,270.506011,86.474614,66.884246,NaN,90.755170,13.434063,3,10201,37.04,14.00,44.06,30.02,1667,821
6,Juneau,AK,89.367785,NaN,169.524359,NaN,NaN,NaN,33.031979,NaN,-7777,9302,39.56,10.94,44.96,33.98,11687,823
7,Phoenix,AZ,66.839636,34.146045,200.353735,95.292175,4.228576,5.881798,76.588709,26.895603,3741,1359,71.42,34.34,88.70,54.32,876,0
8,Mesa,AZ,90.427591,30.461339,278.819932,95.648604,2.630878,0.000000,123.888037,30.461339,3592,1462,70.88,27.68,84.56,57.02,943,0
9,Tucson,AZ,111.380086,32.412979,331.288908,84.472751,8.777518,9.298245,119.370537,24.753733,1946,2486,63.50,37.22,82.04,44.96,1390,23
10,Yuma,AZ,89.963936,43.328682,275.588443,129.802519,2.726742,3.322212,139.602654,40.368228,3811,1129,72.32,29.84,87.26,57.38,368,0
11,Little Rock,AR,124.150876,61.015530,334.467534,139.299537,26.681641,25.018769,110.742169,36.937149,2170,3006,62.78,18.68,71.96,53.24,5468,44
12,Fayetteville,AR,136.078645,35.155192,364.645346,88.438439,31.320575,11.478266,115.174324,23.263998,1517,4013,58.28,20.84,68.54,47.66,4553,43
13,Fort Smith,AR,113.799440,NaN,282.491408,NaN,37.946755,NaN,79.046639,NaN,2053,3244,61.70,22.28,72.86,50.54,5041,46
14,Jonesboro,AR,128.053377,NaN,358.951702,NaN,21.670569,NaN,110.097287,NaN,1735,3846,59.18,21.92,70.16,48.20,4823,48
15,Conway,AR,113.451620,38.979745,312.372626,122.396399,22.037656,0.037681,94.732085,38.123944,1843,3472,60.44,22.82,71.96,49.10,4908,41
16,Los Angeles,CA,81.087951,27.359427,220.286297,54.786719,16.832243,14.489057,87.060861,12.482543,1638,880,67.10,22.64,78.44,55.76,2297,0
17,San Francisco,CA,64.640986,40.110887,158.428255,64.415370,16.371552,31.042033,62.009912,11.273363,174,2701,58.10,19.40,67.82,48.38,2674,0
18,San Diego,CA,60.451393,32.116250,145.160327,62.232609,21.450765,18.474799,52.791774,13.641363,1241,1909,63.14,21.92,74.12,52.16,1677,1
19,San Jose,CA,81.370193,34.099588,222.419115,63.062242,15.928660,20.914838,79.824916,12.882705,395,2735,58.64,30.20,73.76,43.52,5048,1
20,Denver,CO,96.393579,41.870882,222.062377,98.117881,39.046700,15.919006,60.529204,25.952758,15,8879,40.64,31.64,56.66,24.80,1773,857
21,Colorado Springs,CO,109.031245,63.695016,263.506472,106.583514,37.605513,43.550232,73.671774,19.055994,6,9474,39.02,27.32,52.88,25.34,1882,249
22,Fort Collins,CO,65.148913,36.452121,130.824530,89.902512,33.549288,11.749832,29.391001,24.702289,250,7381,45.32,22.64,56.66,34.16,2162,1661
23,Pueblo,CO,133.108033,NaN,356.421142,NaN,29.821025,NaN,114.613892,NaN,1092,5195,53.78,30.56,69.08,38.48,1302,193
24,New Haven,CT,119.555818,44.265730,279.320079,91.052447,46.605382,22.938729,78.071187,14.722778,745,5650,51.44,18.86,60.98,42.08,5110,310
25,Bridgeport,CT,130.564214,NaN,309.549060,NaN,51.325919,NaN,89.636319,14.650037,745,5650,51.44,18.86,60.98,42.08,5110,276
26,Hartford,CT,78.551224,29.069842,167.277800,57.736001,34.538848,23.319241,43.771088,13.409215,603,6318,49.28,21.92,60.26,38.48,5344,313
27,Stamford,CT,93.642628,NaN,248.085028,NaN,18.012045,NaN,74.374634,NaN,799,5443,52.34,21.92,63.14,41.36,5004,312
28,Waterbury,CT,107.866691,NaN,274.893021,NaN,29.454678,NaN,115.041061,13.934902,754,5678,51.44,20.84,61.88,41.00,5110,310
29,Dover,DE,104.369062,44.708310,241.602734,87.177836,41.378846,26.942772,62.785287,19.470050,1314,4269,56.84,18.86,66.38,47.48,4605,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,Chattanooga,TN,96.622230,37.640865,271.289067,99.875055,17.415340,8.763063,92.403689,28.773300,1433,3560,59.18,24.98,71.78,46.58,4499,0
178,Houston,TX,82.477333,55.328099,231.724191,116.792327,12.989201,27.245043,80.580466,28.982608,2586,1469,68.00,18.32,77.18,58.82,5350,0
179,Dallas,TX,88.021084,58.128452,260.472621,141.980934,7.799117,19.415924,85.168085,36.714383,2463,2429,65.12,23.90,77.00,53.06,4015,7
180,San Antonio,TX,96.113849,41.376379,284.631208,103.623493,7.970949,12.584208,105.178000,27.310792,2364,2049,65.84,24.80,78.26,53.42,3810,-7777
181,Austin,TX,83.457189,42.981098,242.526512,93.415740,8.992273,NaN,85.444340,NaN,2710,1918,67.28,24.26,79.16,55.04,3489,6
182,Salt Lake City,UT,134.568281,66.467716,315.097126,107.489209,52.629191,48.475668,82.400703,17.200833,21,9639,38.66,18.32,47.84,29.48,5423,5461
183,Provo,UT,93.406771,NaN,234.716828,NaN,NaN,NaN,NaN,NaN,662,5962,50.54,24.62,62.78,38.12,2053,698
184,Ogden,UT,149.525761,50.792128,346.195750,84.463432,62.420204,35.896579,97.167726,15.695421,1174,5670,52.70,17.24,61.34,44.06,1338,485
185,Logan,UT,138.058773,NaN,299.186121,NaN,64.113704,NaN,73.889033,NaN,704,6680,48.56,21.74,59.54,37.76,1776,415
186,Burlington,VT,92.676069,NaN,249.731546,NaN,19.151181,NaN,77.804001,NaN,484,7432,45.86,18.68,55.22,36.68,3104,852
187,Virginia Beach,VA,69.980373,58.197400,195.849460,121.341974,11.411926,29.376968,62.971897,27.777557,1647,3215,60.62,16.52,69.08,52.34,5079,58
188,Norfolk,VA,96.194558,NaN,270.941833,NaN,13.355791,NaN,86.462865,NaN,1836,2958,61.88,17.06,70.34,53.42,5079,49
189,Richmond,VA,112.704521,43.936039,315.214114,103.406177,18.722155,16.625876,100.204312,19.247214,1292,4096,57.38,20.66,67.64,46.94,4341,165
190,Hampton,VA,97.878375,38.027843,271.507662,99.753041,19.020005,10.249316,86.789857,28.686374,1836,2958,61.88,17.06,70.34,53.42,5079,49
191,Roanoke,VA,84.184330,NaN,201.626666,NaN,30.615587,NaN,55.884772,NaN,1061,4354,55.94,23.54,67.64,44.24,4711,213
192,Seattle,WA,79.723243,36.055703,195.353594,90.929735,26.399558,25.045394,95.486408,25.535467,165,4919,51.98,16.88,60.44,43.52,5637,35
193,Tacoma,WA,129.815255,NaN,364.745391,NaN,21.408599,NaN,141.280182,NaN,223,4531,53.24,17.24,61.88,44.60,3914,48
194,Vancouver,WA,93.065338,NaN,246.031284,NaN,21.298654,NaN,72.812822,NaN,330,4447,53.78,21.20,64.22,43.16,4058,28
195,Everett,WA,135.191433,NaN,344.729678,NaN,37.774922,NaN,105.176329,NaN,111,4937,51.80,17.78,60.62,42.98,3844,25
196,Spokane,WA,134.096878,NaN,334.870437,NaN,40.508535,NaN,94.665363,NaN,249,7139,46.04,21.74,57.02,35.24,1708,541
197,Huntington,WV,111.211455,NaN,256.794242,NaN,41.882126,NaN,75.172442,8.694155,948,5223,53.24,21.38,63.86,42.62,4413,68
198,Morgantown,WV,117.756677,NaN,267.351905,NaN,17.273913,NaN,68.456991,NaN,744,5709,51.44,22.46,62.60,40.28,3958,378
199,Wheeling,WV,97.567017,NaN,240.380868,NaN,32.459815,NaN,61.077689,NaN,909,5303,53.06,21.74,63.86,42.08,4256,171
200,Milwaukee,WI,112.403837,61.219314,248.796168,93.838426,50.805827,48.327908,63.276562,14.606104,568,7304,46.58,18.50,55.76,37.22,3450,359
201,Madison,WI,125.285525,55.601269,303.706252,86.489930,43.368531,42.304402,86.972623,13.684957,597,7283,46.76,21.38,57.38,35.96,3727,379
202,Green Bay,WI,92.159108,22.648930,222.376025,47.659936,30.730914,23.629515,59.517960,10.534924,358,7885,44.42,18.50,53.60,35.06,3127,514
203,Cheyenne,WY,111.067800,NaN,258.143498,NaN,41.147110,NaN,70.353458,NaN,364,7170,46.22,30.92,61.88,30.92,1727,512
204,Casper,WY,118.813999,NaN,296.798243,NaN,32.854181,NaN,81.751226,NaN,314,7866,44.24,25.88,57.20,31.46,1301,734
205,Gillette,WY,110.658160,NaN,268.584859,NaN,35.230860,NaN,68.486712,NaN,522,7375,46.22,26.06,59.18,33.26,1694,588
206,Laramie,WY,79.391602,NaN,179.518493,NaN,NaN,NaN,NaN,29.856481,70,8767,41.18,29.12,55.76,26.60,1143,497

Save files

In [21]:
df5.to_csv(os.path.join("Data","combined_data.csv"),index=False)

In [22]:
df6.to_csv(os.path.join("Data","combined_data_residential.csv"),index=False)