In [1]:
import pandas as pd
import numpy as np
import requests
import json
import os
from config import username, api_key

In [2]:
city_path = os.path.join("Data","usa_cities.csv")
df = pd.read_csv(city_path)
df.head()

,city,city_ascii,lat,lng,pop,country,iso2,iso3,province,abbr
0,Calais,Calais,45.165989,-67.242392,1781.5,United States of America,US,USA,Maine,NaN
1,Houlton,Houlton,46.125517,-67.839720,6051.5,United States of America,US,USA,Maine,NaN
2,Presque Isle,Presque Isle,46.793409,-68.002165,9466.0,United States of America,US,USA,Maine,NaN
3,Bar Harbor,Bar Harbor,44.387897,-68.204375,4483.5,United States of America,US,USA,Maine,NaN
4,Bangor,Bangor,44.801153,-68.778345,40843.0,United States of America,US,USA,Maine,NaN

In [3]:
df_test = df.sort_values(by=["province", "pop"],ascending=False)

In [6]:
def my_func(pops):
    return list(pops[:5])
df_city_list = df_test.groupby("province").agg({"pop": my_func, "city": my_func})

In [7]:
df_city_list = df_city_list.reset_index()
df_city_list

,province,pop,city
0,Alabama,"[670142.0, 221870.0, 194491.5, 185474.5, 10059...","[Birmingham, Mobile, Montgomery, Huntsville, T..."
1,Alaska,"[252068.0, 43608.5, 26172.0, 9848.0, 8521.0]","[Anchorage, Fairbanks, Juneau, Palmer, Wasilla]"
2,Arizona,"[2436022.5, 762217.5, 670953.5, 363360.5, 8840...","[Phoenix, Mesa, Tucson, Glendale, Yuma]"
3,Arkansas,"[227555.0, 108267.5, 87986.5, 58322.0, 56759.5]","[Little Rock, Fayetteville, Fort Smith, Jonesb..."
4,California,"[8097410.0, 2091036.0, 1938570.5, 1611303.5, 1...","[Los Angeles, San Francisco, San Diego, Irvine..."
5,Colorado,"[1930799.5, 431966.5, 427272.0, 178818.5, 1082...","[Denver, Aurora, Colorado Springs, Fort Collin..."
6,Connecticut,"[707883.0, 578545.0, 518509.5, 434781.5, 17423...","[New Haven, Bridgeport, Hartford, Stamford, Wa..."
7,Delaware,"[116205.5, 54662.5]","[Wilmington, Dover]"
8,District of Columbia,[2445216.5],"[Washington, D.C.]"
9,Florida,"[2983947.0, 1319232.5, 1103781.5, 904953.5, 77...","[Miami, Tampa, Fort Lauderdale, Jacksonville, ..."
10,Georgia,"[2464454.0, 202225.0, 155848.5, 152895.5, 1049...","[Atlanta, Columbus, Savannah, Augusta, Macon]"
11,Hawaii,"[578828.5, 95336.0, 47720.5, 32769.5, 10694.5]","[Honolulu, Wahiawa, Hilo, Wailuku, Lihue]"
12,Idaho,"[242029.0, 83403.0, 65787.0, 57327.0, 42958.5]","[Boise, Caldwell, Idaho Falls, Pocatello, Twin..."
13,Illinois,"[5915976.0, 362946.5, 273949.5, 244050.0, 2122...","[Chicago, Joliet, Aurora, Elgin, Evanston]"
14,Indiana,"[1104641.5, 335737.0, 264793.0, 171791.0, 1447...","[Indianapolis, Gary, Fort Wayne, South Bend, E..."
15,Iowa,"[286917.5, 178282.5, 149338.5, 87090.0, 82091.5]","[Des Moines, Davenport, Cedar Rapids, Sioux Ci..."
16,Kansas,"[378543.5, 324221.5, 126830.5, 88020.0, 51289.0]","[Wichita, Kansas City, Topeka, Lawrence, Manha..."
17,Kentucky,"[595819.5, 313064.5, 244972.0, 61349.0, 61151.5]","[Louisville, Covington, Lexington, Bowling Gre..."
18,Louisiana,"[527428.5, 322710.5, 270171.0, 224099.0, 13520...","[New Orleans, Baton Rouge, Metairie, Shrevepor..."
19,Maine,"[99504.0, 46689.0, 40843.0, 21301.0, 20529.0]","[Portland, Lewiston, Bangor, Augusta, Waterville]"
20,Maryland,"[1432946.0, 58776.0, 58487.5, 52792.0, 20831.5]","[Baltimore, Annapolis, Hagerstown, St. Charles..."
21,Massachusetts,"[2528070.5, 415074.0, 287003.5, 232290.5, 1889...","[Boston, Lowell, Springfield, Worcester, Salem]"
22,Michigan,"[2526135.0, 361934.5, 206235.0, 198821.5, 1898...","[Detroit, Grand Rapids, Flint, Lansing, Ann Ar..."
23,Minnesota,"[1491886.5, 509961.0, 156151.0, 102433.0, 8597...","[Minneapolis, St. Paul, Lakeville, Rochester, ..."
24,Mississippi,"[213799.0, 79923.0, 76646.0, 53498.5, 43857.0]","[Jackson, Southaven, Gulfport, Hattiesburg, Bi..."
25,Missouri,"[1259958.0, 955272.5, 244754.0, 213139.5, 1806...","[St. Louis, Kansas City, Columbia, St. Charles..."
26,Montana,"[102151.5, 68010.0, 61316.5, 39049.5, 33032.5]","[Billings, Missoula, Great Falls, Bozeman, Hel..."
27,Nebraska,"[643034.0, 244146.0, 45208.5, 30155.5, 24709.5]","[Omaha, Lincoln, Grand Island, Kearney, North ..."
28,Nevada,"[1150717.0, 265363.5, 53767.0, 17537.0, 15072.5]","[Las Vegas, Reno, Carson City, Elko, Boulder C..."
29,New Hampshire,"[153221.5, 42646.5]","[Manchester, Concord]"
30,New Jersey,"[280123.0, 225713.0, 151205.0, 58563.5]","[Newark, Trenton, Paterson, Atlantic City]"
31,New Mexico,"[725723.0, 97675.5, 80943.0, 45082.5, 42917.5]","[Albuquerque, Las Cruces, Santa Fe, Roswell, F..."
32,New York,"[13524139.0, 647778.5, 484286.0, 483177.0, 403...","[New York, Buffalo, Albany, Rochester, Syracuse]"
33,North Carolina,"[943574.5, 789991.5, 310328.0, 257114.5, 23749...","[Charlotte, Raleigh, Greensboro, Durham, Winst..."
34,North Dakota,"[127472.5, 60288.5, 53496.0, 37162.0, 15987.5]","[Fargo, Bismarck, Grand Forks, Minot, Dickinson]"
35,Ohio,"[1169757.0, 1003418.0, 971191.0, 466067.0, 451...","[Cleveland, Columbus, Cincinnati, Dayton, Akron]"
36,Oklahoma,"[669434.0, 660475.0, 113525.0, 85795.5, 45963.5]","[Tulsa, Oklahoma City, Norman, Lawton, Enid]"
37,Oregon,"[1207756.5, 195183.0, 187966.0, 89081.5, 70598.5]","[Portland, Eugene, Salem, Medford, Bend]"
38,Pennsylvania,"[3504775.0, 1535267.5, 300980.5, 289210.0, 209...","[Philadelphia, Pittsburgh, Allentown, Harrisbu..."
39,Rhode Island,"[663726.5, 35893.0]","[Providence, Newport]"
40,South Carolina,"[257185.5, 254295.0, 203256.5, 81059.0, 77165.0]","[Columbia, Charleston, Greenville, Spartanburg..."
41,South Dakota,"[148030.0, 67760.0, 24854.0, 20313.5, 14973.0]","[Sioux Falls, Rapid City, Aberdeen, Brookings,..."
42,Tennessee,"[753843.5, 703926.0, 417137.0, 206571.5, 16484...","[Memphis, Nashville, Knoxville, Chattanooga, B..."
43,Texas,"[4053287.0, 3004852.0, 1364905.0, 1090830.0, 9...","[Houston, Dallas, San Antonio, Ft. Worth, Austin]"
44,Utah,"[572013.0, 231238.0, 227774.0, 79988.0, 58664.0]","[Salt Lake City, Provo, Ogden, St. George, Logan]"
45,Vermont,"[66204.0, 8183.0]","[Burlington, Montpelier]"
46,Virginia,"[877475.5, 645336.0, 551443.0, 256601.5, 14466...","[Virginia Beach, Norfolk, Richmond, Hampton, R..."
47,Washington,"[1821684.5, 460273.0, 343796.5, 291948.0, 2724...","[Seattle, Tacoma, Vancouver, Everett, Spokane]"
48,West Virginia,"[87113.0, 66957.0, 46749.5, 43882.5, 40940.0]","[Charleston, Huntington, Parkersburg, Morganto..."
49,Wisconsin,"[983590.0, 276036.0, 159012.0, 149811.5, 13688...","[Milwaukee, Madison, Waukesha, Green Bay, Appl..."
50,Wyoming,"[64185.0, 56149.0, 26107.0, 25587.5, 10350.0]","[Cheyenne, Casper, Gillette, Laramie, Riverton]"

In [16]:
clist = []
for cities in df_city_list["city"]:
    clist.extend(cities)
print(clist)

['Birmingham', 'Mobile', 'Montgomery', 'Huntsville', 'Tuscaloosa', 'Anchorage', 'Fairbanks', 'Juneau', 'Palmer', 'Wasilla', 'Phoenix', 'Mesa', 'Tucson', 'Glendale', 'Yuma', 'Little Rock', 'Fayetteville', 'Fort Smith', 'Jonesboro', 'Conway', 'Los Angeles', 'San Francisco', 'San Diego', 'Irvine', 'San Jose', 'Denver', 'Aurora', 'Colorado Springs', 'Fort Collins', 'Pueblo', 'New Haven', 'Bridgeport', 'Hartford', 'Stamford', 'Waterbury', 'Wilmington', 'Dover', 'Washington, D.C.', 'Miami', 'Tampa', 'Fort Lauderdale', 'Jacksonville', 'Orlando', 'Atlanta', 'Columbus', 'Savannah', 'Augusta', 'Macon', 'Honolulu', 'Wahiawa', 'Hilo', 'Wailuku', 'Lihue', 'Boise', 'Caldwell', 'Idaho Falls', 'Pocatello', 'Twin Falls', 'Chicago', 'Joliet', 'Aurora', 'Elgin', 'Evanston', 'Indianapolis', 'Gary', 'Fort Wayne', 'South Bend', 'Evansville', 'Des Moines', 'Davenport', 'Cedar Rapids', 'Sioux City', 'Waterloo', 'Wichita', 'Kansas City', 'Topeka', 'Lawrence', 'Manhattan', 'Louisville', 'Covington', 'Lexington', 'Bowling Green', 'Owensboro', 'New Orleans', 'Baton Rouge', 'Metairie', 'Shreveport', 'Lafayette', 'Portland', 'Lewiston', 'Bangor', 'Augusta', 'Waterville', 'Baltimore', 'Annapolis', 'Hagerstown', 'St. Charles', 'Cumberland', 'Boston', 'Lowell', 'Springfield', 'Worcester', 'Salem', 'Detroit', 'Grand Rapids', 'Flint', 'Lansing', 'Ann Arbor', 'Minneapolis', 'St. Paul', 'Lakeville', 'Rochester', 'St. Cloud', 'Jackson', 'Southaven', 'Gulfport', 'Hattiesburg', 'Biloxi', 'St. Louis', 'Kansas City', 'Columbia', 'St. Charles', 'Springfield', 'Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena', 'Omaha', 'Lincoln', 'Grand Island', 'Kearney', 'North Platte', 'Las Vegas', 'Reno', 'Carson City', 'Elko', 'Boulder City', 'Manchester', 'Concord', 'Newark', 'Trenton', 'Paterson', 'Atlantic City', 'Albuquerque', 'Las Cruces', 'Santa Fe', 'Roswell', 'Farmington', 'New York', 'Buffalo', 'Albany', 'Rochester', 'Syracuse', 'Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'Dickinson', 'Cleveland', 'Columbus', 'Cincinnati', 'Dayton', 'Akron', 'Tulsa', 'Oklahoma City', 'Norman', 'Lawton', 'Enid', 'Portland', 'Eugene', 'Salem', 'Medford', 'Bend', 'Philadelphia', 'Pittsburgh', 'Allentown', 'Harrisburg', 'Lancaster', 'Providence', 'Newport', 'Columbia', 'Charleston', 'Greenville', 'Spartanburg', 'Rock Hill', 'Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Mitchell', 'Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Barlett', 'Houston', 'Dallas', 'San Antonio', 'Ft. Worth', 'Austin', 'Salt Lake City', 'Provo', 'Ogden', 'St. George', 'Logan', 'Burlington', 'Montpelier', 'Virginia Beach', 'Norfolk', 'Richmond', 'Hampton', 'Roanoke', 'Seattle', 'Tacoma', 'Vancouver', 'Everett', 'Spokane', 'Charleston', 'Huntington', 'Parkersburg', 'Morgantown', 'Wheeling', 'Milwaukee', 'Madison', 'Waukesha', 'Green Bay', 'Appleton', 'Cheyenne', 'Casper', 'Gillette', 'Laramie', 'Riverton']

In [58]:
#Save config information
url = "https://bpd-api.lbl.gov/api/v2/analyze/table"

# Build query URL
# params = {
#     "units":"imperial"
# }

energy_data = pd.DataFrame(clist,columns=["City"])
bad_cities = []
site_eui = []
number_of_people = []
operating_hours = []
occupant_density = []
floor_area = []
source_eui = []
num_buildings = []


headers = {
    "Content-Type":"application/json",
    "Authorization":f"ApiKey {username}:{api_key}",
}

energy_data

                 City
0          Birmingham
1              Mobile
2          Montgomery
3          Huntsville
4          Tuscaloosa
5           Anchorage
6           Fairbanks
7              Juneau
8              Palmer
9             Wasilla
10            Phoenix
11               Mesa
12             Tucson
13           Glendale
14               Yuma
15        Little Rock
16       Fayetteville
17         Fort Smith
18          Jonesboro
19             Conway
20        Los Angeles
21      San Francisco
22          San Diego
23             Irvine
24           San Jose
25             Denver
26             Aurora
27   Colorado Springs
28       Fort Collins
29             Pueblo
..                ...
208             Ogden
209        St. George
210             Logan
211        Burlington
212        Montpelier
213    Virginia Beach
214           Norfolk
215          Richmond
216           Hampton
217           Roanoke
218           Seattle
219            Tacoma
220         Vancouver
221           Everett
222           Spokane
223        Charleston
224        Huntington
225       Parkersburg
226        Morgantown
227          Wheeling
228         Milwaukee
229           Madison
230          Waukesha
231         Green Bay
232          Appleton
233          Cheyenne
234            Casper
235          Gillette
236           Laramie
237          Riverton

[238 rows x 1 columns]

In [92]:
payload = {
        "filters":{"city":["Austin"]},
        "group_by":["building_class"],
        "analyze_by":"source_eui"
    }
    
response = requests.post(url=url,data=json.dumps(payload),headers=headers,verify=True)
res_json = response.json()
res_json

{'metadata': {'message': 'success',
  'request_time': 0.09119701385498047,
  'url': 'http://bpd.lbl.gov/developers#analyze/table',
  'version': '2.2.1'},
 'summary': {'count': 742,
  'group': 'ALL',
  'mean': 168.77495809036225,
  'percentile_0': 15.038510023332037,
  'percentile_100': 1173.830590102097,
  'percentile_25': 84.90418970358081,
  'percentile_50': 117.21097097898975,
  'percentile_75': 196.73645864791632,
  'standard_deviation': 149.85814347601007},
 'table': [{'count': 0,
   'group': [{'field': 'building_class',
     'type': 'categorical',
     'value': 'Unknown'}],
   'mean': None,
   'percentile_0': None,
   'percentile_100': None,
   'percentile_25': None,
   'percentile_50': None,
   'percentile_75': None,
   'standard_deviation': None},
  {'count': 367,
   'group': [{'field': 'building_class',
     'type': 'categorical',
     'value': 'Residential'}],
   'mean': 93.41574038481505,
   'percentile_0': 15.038510023332037,
   'percentile_100': 245.81461519350228,
   'percentile_25': 69.14821568146536,
   'percentile_50': 89.87514098512307,
   'percentile_75': 110.1731360862604,
   'standard_deviation': 35.697199744297315},
  {'count': 375,
   'group': [{'field': 'building_class',
     'type': 'categorical',
     'value': 'Commercial'}],
   'mean': 242.52651248485782,
   'percentile_0': 27.303018218321544,
   'percentile_100': 1173.830590102097,
   'percentile_25': 137.49410886951674,
   'percentile_50': 193.97068290960874,
   'percentile_75': 269.095386761076,
   'standard_deviation': 179.50212139825862}],
 'totals': {'number_of_buildings_in_bpd': 1008855,
  'number_of_matching_buildings': 742}}

In [93]:
res_json["table"][2]

{'count': 375,
 'group': [{'field': 'building_class',
   'type': 'categorical',
   'value': 'Commercial'}],
 'mean': 242.52651248485782,
 'percentile_0': 27.303018218321544,
 'percentile_100': 1173.830590102097,
 'percentile_25': 137.49410886951674,
 'percentile_50': 193.97068290960874,
 'percentile_75': 269.095386761076,
 'standard_deviation': 179.50212139825862}

In [94]:
for city in clist:
    payload = {
        "filters":{"city":[city]},
        "group_by":["building_class"],
        "analyze_by":"source_eui"
    }
    
    try:
        response = requests.post(url=url,data=json.dumps(payload),headers=headers,verify=True)
        res_json = response.json()
        source_eui.append(res_json["table"][2]["mean"])
        print(f"Processing Record : {city}")
        
    except:
        print(f"Missing Data : {city}")
        source_eui.append(np.nan)

Processing Record : Birmingham
Processing Record : Mobile
Processing Record : Montgomery
Processing Record : Huntsville
Processing Record : Tuscaloosa
Processing Record : Anchorage
Missing Data : Fairbanks
Processing Record : Juneau
Processing Record : Palmer
Missing Data : Wasilla
Processing Record : Phoenix
Processing Record : Mesa
Processing Record : Tucson
Processing Record : Glendale
Processing Record : Yuma
Processing Record : Little Rock
Processing Record : Fayetteville
Processing Record : Fort Smith
Processing Record : Jonesboro
Processing Record : Conway
Processing Record : Los Angeles
Processing Record : San Francisco
Processing Record : San Diego
Processing Record : Irvine
Processing Record : San Jose
Processing Record : Denver
Processing Record : Aurora
Processing Record : Colorado Springs
Processing Record : Fort Collins
Processing Record : Pueblo
Processing Record : New Haven
Processing Record : Bridgeport
Processing Record : Hartford
Processing Record : Stamford
Processing Record : Waterbury
Processing Record : Wilmington
Processing Record : Dover
Processing Record : Washington, D.C.
Processing Record : Miami
Processing Record : Tampa
Processing Record : Fort Lauderdale
Processing Record : Jacksonville
Processing Record : Orlando
Processing Record : Atlanta
Processing Record : Columbus
Processing Record : Savannah
Processing Record : Augusta
Processing Record : Macon
Processing Record : Honolulu
Missing Data : Wahiawa
Processing Record : Hilo
Processing Record : Wailuku
Missing Data : Lihue
Processing Record : Boise
Processing Record : Caldwell
Processing Record : Idaho Falls
Processing Record : Pocatello
Processing Record : Twin Falls
Processing Record : Chicago
Processing Record : Joliet
Processing Record : Aurora
Processing Record : Elgin
Processing Record : Evanston
Processing Record : Indianapolis
Missing Data : Gary
Processing Record : Fort Wayne
Processing Record : South Bend
Processing Record : Evansville
Processing Record : Des Moines
Processing Record : Davenport
Processing Record : Cedar Rapids
Processing Record : Sioux City
Processing Record : Waterloo
Processing Record : Wichita
Processing Record : Kansas City
Processing Record : Topeka
Processing Record : Lawrence
Processing Record : Manhattan
Processing Record : Louisville
Processing Record : Covington
Processing Record : Lexington
Processing Record : Bowling Green
Processing Record : Owensboro
Processing Record : New Orleans
Processing Record : Baton Rouge
Processing Record : Metairie
Processing Record : Shreveport
Processing Record : Lafayette
Processing Record : Portland
Processing Record : Lewiston
Processing Record : Bangor
Processing Record : Augusta
Missing Data : Waterville
Processing Record : Baltimore
Processing Record : Annapolis
Processing Record : Hagerstown
Processing Record : St. Charles
Processing Record : Cumberland
Processing Record : Boston
Processing Record : Lowell
Processing Record : Springfield
Processing Record : Worcester
Processing Record : Salem
Processing Record : Detroit
Processing Record : Grand Rapids
Processing Record : Flint
Processing Record : Lansing
Processing Record : Ann Arbor
Processing Record : Minneapolis
Processing Record : St. Paul
Processing Record : Lakeville
Processing Record : Rochester
Processing Record : St. Cloud
Processing Record : Jackson
Processing Record : Southaven
Processing Record : Gulfport
Processing Record : Hattiesburg
Missing Data : Biloxi
Missing Data : St. Louis
Processing Record : Kansas City
Processing Record : Columbia
Processing Record : St. Charles
Processing Record : Springfield
Processing Record : Billings
Processing Record : Missoula
Processing Record : Great Falls
Processing Record : Bozeman
Processing Record : Helena
Processing Record : Omaha
Processing Record : Lincoln
Processing Record : Grand Island
Processing Record : Kearney
Processing Record : North Platte
Processing Record : Las Vegas
Processing Record : Reno
Processing Record : Carson City
Processing Record : Elko
Processing Record : Boulder City
Processing Record : Manchester
Processing Record : Concord
Processing Record : Newark
Processing Record : Trenton
Missing Data : Paterson
Missing Data : Atlantic City
Processing Record : Albuquerque
Processing Record : Las Cruces
Processing Record : Santa Fe
Processing Record : Roswell
Processing Record : Farmington
Processing Record : New York
Processing Record : Buffalo
Processing Record : Albany
Processing Record : Rochester
Processing Record : Syracuse
Processing Record : Charlotte
Processing Record : Raleigh
Processing Record : Greensboro
Processing Record : Durham
Processing Record : Winston-Salem
Processing Record : Fargo
Processing Record : Bismarck
Processing Record : Grand Forks
Processing Record : Minot
Processing Record : Dickinson
Processing Record : Cleveland
Processing Record : Columbus
Processing Record : Cincinnati
Processing Record : Dayton
Processing Record : Akron
Processing Record : Tulsa
Processing Record : Oklahoma City
Processing Record : Norman
Processing Record : Lawton
Missing Data : Enid
Processing Record : Portland
Processing Record : Eugene
Processing Record : Salem
Processing Record : Medford
Processing Record : Bend
Processing Record : Philadelphia
Processing Record : Pittsburgh
Processing Record : Allentown
Processing Record : Harrisburg
Processing Record : Lancaster
Processing Record : Providence
Processing Record : Newport
Processing Record : Columbia
Processing Record : Charleston
Processing Record : Greenville
Processing Record : Spartanburg
Processing Record : Rock Hill
Processing Record : Sioux Falls
Processing Record : Rapid City
Processing Record : Aberdeen
Missing Data : Brookings
Missing Data : Mitchell
Processing Record : Memphis
Processing Record : Nashville
Processing Record : Knoxville
Processing Record : Chattanooga
Processing Record : Barlett
Processing Record : Houston
Processing Record : Dallas
Processing Record : San Antonio
Processing Record : Ft. Worth
Processing Record : Austin
Processing Record : Salt Lake City
Processing Record : Provo
Processing Record : Ogden
Processing Record : St. George
Processing Record : Logan
Processing Record : Burlington
Missing Data : Montpelier
Processing Record : Virginia Beach
Processing Record : Norfolk
Processing Record : Richmond
Processing Record : Hampton
Processing Record : Roanoke
Processing Record : Seattle
Processing Record : Tacoma
Processing Record : Vancouver
Processing Record : Everett
Processing Record : Spokane
Processing Record : Charleston
Processing Record : Huntington
Missing Data : Parkersburg
Processing Record : Morgantown
Processing Record : Wheeling
Processing Record : Milwaukee
Processing Record : Madison
Processing Record : Waukesha
Processing Record : Green Bay
Processing Record : Appleton
Processing Record : Cheyenne
Processing Record : Casper
Processing Record : Gillette
Processing Record : Laramie
Processing Record : Riverton

In [95]:
energy_data["mean source eui"] = source_eui
energy_data

,City,mean site eui,mean number of people,mean operating hours,mean occupant density,mean floor area,mean source eui
0,Birmingham,143.647642,356.923077,68.808462,2.025053,115640.118583,400.595034
1,Mobile,107.084979,NaN,NaN,NaN,70016.914000,315.907443
2,Montgomery,112.048215,NaN,NaN,NaN,82585.243820,298.702917
3,Huntsville,116.235841,NaN,NaN,NaN,37496.988994,362.019120
4,Tuscaloosa,189.021112,NaN,NaN,NaN,119205.349500,514.514461
5,Anchorage,133.111653,NaN,NaN,NaN,113163.470000,270.506011
6,Fairbanks,NaN,NaN,NaN,NaN,NaN,NaN
7,Juneau,89.367785,NaN,NaN,NaN,126827.532000,169.524359
8,Palmer,116.003042,NaN,NaN,NaN,26812.928571,158.043371
9,Wasilla,NaN,NaN,NaN,NaN,NaN,NaN
10,Phoenix,66.839636,247.945122,66.161159,2.417184,141551.863097,200.353735
11,Mesa,90.427591,127.700000,99.154000,1.635223,65555.670938,278.819932
12,Tucson,111.380086,105.714286,105.190893,1.322175,77062.206205,331.288909
13,Glendale,75.822699,424.000000,80.197111,2.010290,159690.979195,219.851930
14,Yuma,89.963936,NaN,NaN,NaN,56023.513243,275.588443
15,Little Rock,124.150876,403.272727,107.318182,2.269219,113052.336212,334.467534
16,Fayetteville,136.078645,NaN,NaN,NaN,66337.030225,364.645346
17,Fort Smith,113.799440,NaN,NaN,NaN,94551.483600,282.491408
18,Jonesboro,128.053377,NaN,NaN,NaN,65864.722222,358.951702
19,Conway,113.451620,NaN,NaN,NaN,67215.833333,312.372626
20,Los Angeles,81.087951,1019.349057,63.419112,2.631776,348019.742446,220.286297
21,San Francisco,64.640986,926.949045,67.745936,2.656458,161101.554825,158.428255
22,San Diego,60.451393,361.581967,62.641382,2.627188,89564.365707,145.160327
23,Irvine,62.142030,465.813333,56.345761,2.595104,137933.815956,168.017955
24,San Jose,81.370193,384.400000,67.045390,2.599932,105589.157907,222.419115
25,Denver,96.393579,638.220000,66.386765,2.398287,167341.567033,222.062377
26,Aurora,101.436132,176.259259,80.208889,1.639689,86601.809957,251.943943
27,Colorado Springs,109.031245,479.000000,81.554545,2.620595,94735.161111,263.506472
28,Fort Collins,65.148913,NaN,NaN,NaN,90923.758278,130.824530
29,Pueblo,133.108033,NaN,NaN,NaN,55546.181818,356.421142
...,...,...,...,...,...,...,...
208,Ogden,149.525761,NaN,NaN,NaN,90514.612174,346.195750
209,St. George,NaN,NaN,NaN,NaN,NaN,NaN
210,Logan,138.058773,NaN,NaN,NaN,86175.714286,299.186121
211,Burlington,92.676069,165.400000,71.695500,1.572702,100636.318990,249.731546
212,Montpelier,NaN,NaN,NaN,NaN,22350.572222,NaN
213,Virginia Beach,69.980373,144.181818,92.608182,2.377143,93877.976447,195.849460
214,Norfolk,96.194558,621.600000,69.898000,2.822722,139467.565660,270.941832
215,Richmond,112.704521,324.184211,76.794727,2.294704,124285.721706,315.214114
216,Hampton,97.878375,NaN,NaN,NaN,47657.257984,271.507662
217,Roanoke,84.184330,NaN,NaN,NaN,83955.175659,201.626666
218,Seattle,79.723243,942.616438,63.361812,2.543029,120734.853017,195.353594
219,Tacoma,129.815255,NaN,NaN,NaN,138851.047797,364.745391
220,Vancouver,93.065338,NaN,NaN,NaN,77988.879630,246.031284
221,Everett,135.191433,275.600000,64.521500,2.178689,99452.878049,344.729678
222,Spokane,134.096878,224.578947,75.030000,1.581039,83641.229909,334.870437
223,Charleston,124.496181,NaN,NaN,NaN,92774.344085,341.583570
224,Huntington,111.211455,NaN,NaN,NaN,47066.776604,256.794242
225,Parkersburg,NaN,NaN,NaN,NaN,NaN,NaN
226,Morgantown,117.756677,NaN,NaN,NaN,48879.100000,267.351905
227,Wheeling,97.567017,NaN,NaN,NaN,58477.240769,240.380868
228,Milwaukee,112.403837,481.125000,85.912092,1.921060,111891.420684,248.796169
229,Madison,125.285525,195.533333,87.102283,1.619649,104573.191148,303.706252
230,Waukesha,114.124402,NaN,NaN,NaN,68200.952414,281.617128
231,Green Bay,92.159108,NaN,NaN,NaN,110269.061224,222.376025
232,Appleton,89.422308,NaN,NaN,NaN,112723.451613,204.605858
233,Cheyenne,111.067800,NaN,NaN,NaN,129977.905769,258.143498
234,Casper,118.813999,NaN,NaN,NaN,66967.902381,296.798243
235,Gillette,110.658160,NaN,NaN,NaN,43648.375000,268.584859
236,Laramie,79.391602,NaN,NaN,NaN,39724.100000,179.518493
237,Riverton,130.309810,NaN,NaN,NaN,59840.211111,297.670463

In [96]:
energy_data.to_csv(os.path.join("Data","bpd_data.csv"))

In [101]:
energy_data_clean = energy_data.dropna()
energy_data_clean = energy_data_clean

,City,mean site eui,mean number of people,mean operating hours,mean occupant density,mean floor area,mean source eui
0,Birmingham,143.647642,356.923077,68.808462,2.025053,115640.118583,400.595034
10,Phoenix,66.839636,247.945122,66.161159,2.417184,141551.863097,200.353735
11,Mesa,90.427591,127.700000,99.154000,1.635223,65555.670938,278.819932
12,Tucson,111.380086,105.714286,105.190893,1.322175,77062.206205,331.288909
13,Glendale,75.822699,424.000000,80.197111,2.010290,159690.979195,219.851930
15,Little Rock,124.150876,403.272727,107.318182,2.269219,113052.336212,334.467534
20,Los Angeles,81.087951,1019.349057,63.419112,2.631776,348019.742446,220.286297
21,San Francisco,64.640986,926.949045,67.745936,2.656458,161101.554825,158.428255
22,San Diego,60.451393,361.581967,62.641382,2.627188,89564.365707,145.160327
23,Irvine,62.142030,465.813333,56.345761,2.595104,137933.815956,168.017955
24,San Jose,81.370193,384.400000,67.045390,2.599932,105589.157907,222.419115
25,Denver,96.393579,638.220000,66.386765,2.398287,167341.567033,222.062377
26,Aurora,101.436132,176.259259,80.208889,1.639689,86601.809957,251.943943
27,Colorado Springs,109.031245,479.000000,81.554545,2.620595,94735.161111,263.506472
35,Wilmington,94.046483,201.666667,72.226562,1.838126,95805.844864,248.102622
36,Dover,104.369062,186.384615,77.038462,1.261553,62634.188350,241.602734
38,Miami,80.034867,564.676056,59.227956,2.583499,201358.742975,244.493920
39,Tampa,77.431934,561.484848,73.363358,2.882281,218449.159966,234.082671
40,Fort Lauderdale,87.295570,456.176471,57.483775,3.304424,116036.868018,265.202279
41,Jacksonville,126.601510,438.083333,79.655590,2.486996,98020.998089,348.638448
42,Orlando,80.441852,391.095238,63.441548,2.401224,123194.291064,241.472953
43,Atlanta,76.472647,853.111842,58.493052,2.778760,297161.150357,203.785095
44,Columbus,126.280207,670.200000,77.950865,1.971120,144703.476766,320.647152
48,Honolulu,58.847680,526.944444,64.860443,2.801782,177464.982418,175.626742
53,Boise,104.283147,381.200000,58.382000,2.223806,97617.138857,275.053738
58,Chicago,110.227205,1790.761468,67.238459,2.473650,384232.399655,248.333603
60,Aurora,101.436132,176.259259,80.208889,1.639689,86601.809957,251.943943
63,Indianapolis,132.877553,401.458333,92.890833,2.483596,111189.042139,343.926757
65,Fort Wayne,168.422111,258.900000,95.880000,1.221893,73854.254215,410.926781
68,Des Moines,58.662125,628.400000,75.900000,1.756394,113171.950172,140.374875
...,...,...,...,...,...,...,...
165,Columbus,126.280207,670.200000,77.950865,1.971120,144703.476766,320.647152
166,Cincinnati,106.759494,464.750000,74.261017,1.994058,139670.502219,270.356669
167,Dayton,88.156151,103.500000,71.645583,1.203363,93185.817897,212.330880
168,Akron,126.560927,249.769231,76.978462,1.596176,68065.414875,306.851758
170,Oklahoma City,120.375839,369.600000,63.617333,1.939964,105447.876358,328.523592
174,Portland,89.064103,480.725806,64.560551,2.102094,124450.184124,218.356452
176,Salem,89.425012,102.250000,90.333333,1.463561,75697.271831,222.759544
179,Philadelphia,110.764195,1648.180000,77.292343,2.491419,219390.089532,247.226300
180,Pittsburgh,116.932596,684.523810,89.643333,1.847564,103337.902170,262.027147
182,Harrisburg,150.824440,346.571429,75.860000,1.806203,105081.497368,344.776289
183,Lancaster,130.690697,45.100000,83.700000,0.763676,58559.133645,324.954045
186,Columbia,105.980920,236.567568,66.420219,2.488549,88929.932358,275.182473
188,Greenville,129.742364,273.640000,74.172917,1.970145,87215.741693,334.221041
196,Memphis,112.182507,348.000000,84.018636,1.695682,152962.585915,303.031317
197,Nashville,150.726955,753.523810,83.277262,2.542690,182744.411812,393.698218
198,Knoxville,139.144747,161.076923,67.688750,1.492724,56341.209947,333.294728
201,Houston,82.477333,920.546296,62.202600,2.656543,289531.972942,231.724191
202,Dallas,88.021084,966.965517,62.014830,2.321133,359069.062787,260.472621
203,San Antonio,96.113849,667.442308,77.472436,2.379787,204352.996899,284.631208
205,Austin,83.457189,555.386667,75.252952,3.623255,162501.839010,242.526512
206,Salt Lake City,134.568281,346.040000,98.823590,2.387575,103532.860518,315.097126
211,Burlington,92.676069,165.400000,71.695500,1.572702,100636.318990,249.731546
213,Virginia Beach,69.980373,144.181818,92.608182,2.377143,93877.976447,195.849460
214,Norfolk,96.194558,621.600000,69.898000,2.822722,139467.565660,270.941832
215,Richmond,112.704521,324.184211,76.794727,2.294704,124285.721706,315.214114
218,Seattle,79.723243,942.616438,63.361812,2.543029,120734.853017,195.353594
221,Everett,135.191433,275.600000,64.521500,2.178689,99452.878049,344.729678
222,Spokane,134.096878,224.578947,75.030000,1.581039,83641.229909,334.870437
228,Milwaukee,112.403837,481.125000,85.912092,1.921060,111891.420684,248.796169
229,Madison,125.285525,195.533333,87.102283,1.619649,104573.191148,303.706252

In [105]:
df_city_list_two = df_test.groupby("province").agg({"pop": my_func, "city": my_func, "province":my_func})
df_city_list_two

,pop,city,province
province,,,
Alabama,"[670142.0, 221870.0, 194491.5, 185474.5, 10059...","[Birmingham, Mobile, Montgomery, Huntsville, T...","[Alabama, Alabama, Alabama, Alabama, Alabama]"
Alaska,"[252068.0, 43608.5, 26172.0, 9848.0, 8521.0]","[Anchorage, Fairbanks, Juneau, Palmer, Wasilla]","[Alaska, Alaska, Alaska, Alaska, Alaska]"
Arizona,"[2436022.5, 762217.5, 670953.5, 363360.5, 8840...","[Phoenix, Mesa, Tucson, Glendale, Yuma]","[Arizona, Arizona, Arizona, Arizona, Arizona]"
Arkansas,"[227555.0, 108267.5, 87986.5, 58322.0, 56759.5]","[Little Rock, Fayetteville, Fort Smith, Jonesb...","[Arkansas, Arkansas, Arkansas, Arkansas, Arkan..."
California,"[8097410.0, 2091036.0, 1938570.5, 1611303.5, 1...","[Los Angeles, San Francisco, San Diego, Irvine...","[California, California, California, Californi..."
Colorado,"[1930799.5, 431966.5, 427272.0, 178818.5, 1082...","[Denver, Aurora, Colorado Springs, Fort Collin...","[Colorado, Colorado, Colorado, Colorado, Color..."
Connecticut,"[707883.0, 578545.0, 518509.5, 434781.5, 17423...","[New Haven, Bridgeport, Hartford, Stamford, Wa...","[Connecticut, Connecticut, Connecticut, Connec..."
Delaware,"[116205.5, 54662.5]","[Wilmington, Dover]","[Delaware, Delaware]"
District of Columbia,[2445216.5],"[Washington, D.C.]",[District of Columbia]
Florida,"[2983947.0, 1319232.5, 1103781.5, 904953.5, 77...","[Miami, Tampa, Fort Lauderdale, Jacksonville, ...","[Florida, Florida, Florida, Florida, Florida]"
Georgia,"[2464454.0, 202225.0, 155848.5, 152895.5, 1049...","[Atlanta, Columbus, Savannah, Augusta, Macon]","[Georgia, Georgia, Georgia, Georgia, Georgia]"
Hawaii,"[578828.5, 95336.0, 47720.5, 32769.5, 10694.5]","[Honolulu, Wahiawa, Hilo, Wailuku, Lihue]","[Hawaii, Hawaii, Hawaii, Hawaii, Hawaii]"
Idaho,"[242029.0, 83403.0, 65787.0, 57327.0, 42958.5]","[Boise, Caldwell, Idaho Falls, Pocatello, Twin...","[Idaho, Idaho, Idaho, Idaho, Idaho]"
Illinois,"[5915976.0, 362946.5, 273949.5, 244050.0, 2122...","[Chicago, Joliet, Aurora, Elgin, Evanston]","[Illinois, Illinois, Illinois, Illinois, Illin..."
Indiana,"[1104641.5, 335737.0, 264793.0, 171791.0, 1447...","[Indianapolis, Gary, Fort Wayne, South Bend, E...","[Indiana, Indiana, Indiana, Indiana, Indiana]"
Iowa,"[286917.5, 178282.5, 149338.5, 87090.0, 82091.5]","[Des Moines, Davenport, Cedar Rapids, Sioux Ci...","[Iowa, Iowa, Iowa, Iowa, Iowa]"
Kansas,"[378543.5, 324221.5, 126830.5, 88020.0, 51289.0]","[Wichita, Kansas City, Topeka, Lawrence, Manha...","[Kansas, Kansas, Kansas, Kansas, Kansas]"
Kentucky,"[595819.5, 313064.5, 244972.0, 61349.0, 61151.5]","[Louisville, Covington, Lexington, Bowling Gre...","[Kentucky, Kentucky, Kentucky, Kentucky, Kentu..."
Louisiana,"[527428.5, 322710.5, 270171.0, 224099.0, 13520...","[New Orleans, Baton Rouge, Metairie, Shrevepor...","[Louisiana, Louisiana, Louisiana, Louisiana, L..."
Maine,"[99504.0, 46689.0, 40843.0, 21301.0, 20529.0]","[Portland, Lewiston, Bangor, Augusta, Waterville]","[Maine, Maine, Maine, Maine, Maine]"
Maryland,"[1432946.0, 58776.0, 58487.5, 52792.0, 20831.5]","[Baltimore, Annapolis, Hagerstown, St. Charles...","[Maryland, Maryland, Maryland, Maryland, Maryl..."
Massachusetts,"[2528070.5, 415074.0, 287003.5, 232290.5, 1889...","[Boston, Lowell, Springfield, Worcester, Salem]","[Massachusetts, Massachusetts, Massachusetts, ..."
Michigan,"[2526135.0, 361934.5, 206235.0, 198821.5, 1898...","[Detroit, Grand Rapids, Flint, Lansing, Ann Ar...","[Michigan, Michigan, Michigan, Michigan, Michi..."
Minnesota,"[1491886.5, 509961.0, 156151.0, 102433.0, 8597...","[Minneapolis, St. Paul, Lakeville, Rochester, ...","[Minnesota, Minnesota, Minnesota, Minnesota, M..."
Mississippi,"[213799.0, 79923.0, 76646.0, 53498.5, 43857.0]","[Jackson, Southaven, Gulfport, Hattiesburg, Bi...","[Mississippi, Mississippi, Mississippi, Missis..."
Missouri,"[1259958.0, 955272.5, 244754.0, 213139.5, 1806...","[St. Louis, Kansas City, Columbia, St. Charles...","[Missouri, Missouri, Missouri, Missouri, Misso..."
Montana,"[102151.5, 68010.0, 61316.5, 39049.5, 33032.5]","[Billings, Missoula, Great Falls, Bozeman, Hel...","[Montana, Montana, Montana, Montana, Montana]"
Nebraska,"[643034.0, 244146.0, 45208.5, 30155.5, 24709.5]","[Omaha, Lincoln, Grand Island, Kearney, North ...","[Nebraska, Nebraska, Nebraska, Nebraska, Nebra..."
Nevada,"[1150717.0, 265363.5, 53767.0, 17537.0, 15072.5]","[Las Vegas, Reno, Carson City, Elko, Boulder C...","[Nevada, Nevada, Nevada, Nevada, Nevada]"
New Hampshire,"[153221.5, 42646.5]","[Manchester, Concord]","[New Hampshire, New Hampshire]"
New Jersey,"[280123.0, 225713.0, 151205.0, 58563.5]","[Newark, Trenton, Paterson, Atlantic City]","[New Jersey, New Jersey, New Jersey, New Jersey]"
New Mexico,"[725723.0, 97675.5, 80943.0, 45082.5, 42917.5]","[Albuquerque, Las Cruces, Santa Fe, Roswell, F...","[New Mexico, New Mexico, New Mexico, New Mexic..."
New York,"[13524139.0, 647778.5, 484286.0, 483177.0, 403...","[New York, Buffalo, Albany, Rochester, Syracuse]","[New York, New York, New York, New York, New Y..."
North Carolina,"[943574.5, 789991.5, 310328.0, 257114.5, 23749...","[Charlotte, Raleigh, Greensboro, Durham, Winst...","[North Carolina, North Carolina, North Carolin..."
North Dakota,"[127472.5, 60288.5, 53496.0, 37162.0, 15987.5]","[Fargo, Bismarck, Grand Forks, Minot, Dickinson]","[North Dakota, North Dakota, North Dakota, Nor..."
Ohio,"[1169757.0, 1003418.0, 971191.0, 466067.0, 451...","[Cleveland, Columbus, Cincinnati, Dayton, Akron]","[Ohio, Ohio, Ohio, Ohio, Ohio]"
Oklahoma,"[669434.0, 660475.0, 113525.0, 85795.5, 45963.5]","[Tulsa, Oklahoma City, Norman, Lawton, Enid]","[Oklahoma, Oklahoma, Oklahoma, Oklahoma, Oklah..."
Oregon,"[1207756.5, 195183.0, 187966.0, 89081.5, 70598.5]","[Portland, Eugene, Salem, Medford, Bend]","[Oregon, Oregon, Oregon, Oregon, Oregon]"
Pennsylvania,"[3504775.0, 1535267.5, 300980.5, 289210.0, 209...","[Philadelphia, Pittsburgh, Allentown, Harrisbu...","[Pennsylvania, Pennsylvania, Pennsylvania, Pen..."
Rhode Island,"[663726.5, 35893.0]","[Providence, Newport]","[Rhode Island, Rhode Island]"
South Carolina,"[257185.5, 254295.0, 203256.5, 81059.0, 77165.0]","[Columbia, Charleston, Greenville, Spartanburg...","[South Carolina, South Carolina, South Carolin..."
South Dakota,"[148030.0, 67760.0, 24854.0, 20313.5, 14973.0]","[Sioux Falls, Rapid City, Aberdeen, Brookings,...","[South Dakota, South Dakota, South Dakota, Sou..."
Tennessee,"[753843.5, 703926.0, 417137.0, 206571.5, 16484...","[Memphis, Nashville, Knoxville, Chattanooga, B...","[Tennessee, Tennessee, Tennessee, Tennessee, T..."
Texas,"[4053287.0, 3004852.0, 1364905.0, 1090830.0, 9...","[Houston, Dallas, San Antonio, Ft. Worth, Austin]","[Texas, Texas, Texas, Texas, Texas]"
Utah,"[572013.0, 231238.0, 227774.0, 79988.0, 58664.0]","[Salt Lake City, Provo, Ogden, St. George, Logan]","[Utah, Utah, Utah, Utah, Utah]"
Vermont,"[66204.0, 8183.0]","[Burlington, Montpelier]","[Vermont, Vermont]"
Virginia,"[877475.5, 645336.0, 551443.0, 256601.5, 14466...","[Virginia Beach, Norfolk, Richmond, Hampton, R...","[Virginia, Virginia, Virginia, Virginia, Virgi..."
Washington,"[1821684.5, 460273.0, 343796.5, 291948.0, 2724...","[Seattle, Tacoma, Vancouver, Everett, Spokane]","[Washington, Washington, Washington, Washingto..."
West Virginia,"[87113.0, 66957.0, 46749.5, 43882.5, 40940.0]","[Charleston, Huntington, Parkersburg, Morganto...","[West Virginia, West Virginia, West Virginia, ..."
Wisconsin,"[983590.0, 276036.0, 159012.0, 149811.5, 13688...","[Milwaukee, Madison, Waukesha, Green Bay, Appl...","[Wisconsin, Wisconsin, Wisconsin, Wisconsin, W..."
Wyoming,"[64185.0, 56149.0, 26107.0, 25587.5, 10350.0]","[Cheyenne, Casper, Gillette, Laramie, Riverton]","[Wyoming, Wyoming, Wyoming, Wyoming, Wyoming]"

In [106]:
slist = []
for states in df_city_list_two["province"]:
    slist.extend(states)
print(slist)

['Alabama', 'Alabama', 'Alabama', 'Alabama', 'Alabama', 'Alaska', 'Alaska', 'Alaska', 'Alaska', 'Alaska', 'Arizona', 'Arizona', 'Arizona', 'Arizona', 'Arizona', 'Arkansas', 'Arkansas', 'Arkansas', 'Arkansas', 'Arkansas', 'California', 'California', 'California', 'California', 'California', 'Colorado', 'Colorado', 'Colorado', 'Colorado', 'Colorado', 'Connecticut', 'Connecticut', 'Connecticut', 'Connecticut', 'Connecticut', 'Delaware', 'Delaware', 'District of Columbia', 'Florida', 'Florida', 'Florida', 'Florida', 'Florida', 'Georgia', 'Georgia', 'Georgia', 'Georgia', 'Georgia', 'Hawaii', 'Hawaii', 'Hawaii', 'Hawaii', 'Hawaii', 'Idaho', 'Idaho', 'Idaho', 'Idaho', 'Idaho', 'Illinois', 'Illinois', 'Illinois', 'Illinois', 'Illinois', 'Indiana', 'Indiana', 'Indiana', 'Indiana', 'Indiana', 'Iowa', 'Iowa', 'Iowa', 'Iowa', 'Iowa', 'Kansas', 'Kansas', 'Kansas', 'Kansas', 'Kansas', 'Kentucky', 'Kentucky', 'Kentucky', 'Kentucky', 'Kentucky', 'Louisiana', 'Louisiana', 'Louisiana', 'Louisiana', 'Louisiana', 'Maine', 'Maine', 'Maine', 'Maine', 'Maine', 'Maryland', 'Maryland', 'Maryland', 'Maryland', 'Maryland', 'Massachusetts', 'Massachusetts', 'Massachusetts', 'Massachusetts', 'Massachusetts', 'Michigan', 'Michigan', 'Michigan', 'Michigan', 'Michigan', 'Minnesota', 'Minnesota', 'Minnesota', 'Minnesota', 'Minnesota', 'Mississippi', 'Mississippi', 'Mississippi', 'Mississippi', 'Mississippi', 'Missouri', 'Missouri', 'Missouri', 'Missouri', 'Missouri', 'Montana', 'Montana', 'Montana', 'Montana', 'Montana', 'Nebraska', 'Nebraska', 'Nebraska', 'Nebraska', 'Nebraska', 'Nevada', 'Nevada', 'Nevada', 'Nevada', 'Nevada', 'New Hampshire', 'New Hampshire', 'New Jersey', 'New Jersey', 'New Jersey', 'New Jersey', 'New Mexico', 'New Mexico', 'New Mexico', 'New Mexico', 'New Mexico', 'New York', 'New York', 'New York', 'New York', 'New York', 'North Carolina', 'North Carolina', 'North Carolina', 'North Carolina', 'North Carolina', 'North Dakota', 'North Dakota', 'North Dakota', 'North Dakota', 'North Dakota', 'Ohio', 'Ohio', 'Ohio', 'Ohio', 'Ohio', 'Oklahoma', 'Oklahoma', 'Oklahoma', 'Oklahoma', 'Oklahoma', 'Oregon', 'Oregon', 'Oregon', 'Oregon', 'Oregon', 'Pennsylvania', 'Pennsylvania', 'Pennsylvania', 'Pennsylvania', 'Pennsylvania', 'Rhode Island', 'Rhode Island', 'South Carolina', 'South Carolina', 'South Carolina', 'South Carolina', 'South Carolina', 'South Dakota', 'South Dakota', 'South Dakota', 'South Dakota', 'South Dakota', 'Tennessee', 'Tennessee', 'Tennessee', 'Tennessee', 'Tennessee', 'Texas', 'Texas', 'Texas', 'Texas', 'Texas', 'Utah', 'Utah', 'Utah', 'Utah', 'Utah', 'Vermont', 'Vermont', 'Virginia', 'Virginia', 'Virginia', 'Virginia', 'Virginia', 'Washington', 'Washington', 'Washington', 'Washington', 'Washington', 'West Virginia', 'West Virginia', 'West Virginia', 'West Virginia', 'West Virginia', 'Wisconsin', 'Wisconsin', 'Wisconsin', 'Wisconsin', 'Wisconsin', 'Wyoming', 'Wyoming', 'Wyoming', 'Wyoming', 'Wyoming']

In [108]:
energy_data

,City,mean site eui,mean number of people,mean operating hours,mean occupant density,mean floor area,mean source eui,state
0,Birmingham,143.647642,356.923077,68.808462,2.025053,115640.118583,400.595034,Alabama
1,Mobile,107.084979,NaN,NaN,NaN,70016.914000,315.907443,Alabama
2,Montgomery,112.048215,NaN,NaN,NaN,82585.243820,298.702917,Alabama
3,Huntsville,116.235841,NaN,NaN,NaN,37496.988994,362.019120,Alabama
4,Tuscaloosa,189.021112,NaN,NaN,NaN,119205.349500,514.514461,Alabama
5,Anchorage,133.111653,NaN,NaN,NaN,113163.470000,270.506011,Alaska
6,Fairbanks,NaN,NaN,NaN,NaN,NaN,NaN,Alaska
7,Juneau,89.367785,NaN,NaN,NaN,126827.532000,169.524359,Alaska
8,Palmer,116.003042,NaN,NaN,NaN,26812.928571,158.043371,Alaska
9,Wasilla,NaN,NaN,NaN,NaN,NaN,NaN,Alaska
10,Phoenix,66.839636,247.945122,66.161159,2.417184,141551.863097,200.353735,Arizona
11,Mesa,90.427591,127.700000,99.154000,1.635223,65555.670938,278.819932,Arizona
12,Tucson,111.380086,105.714286,105.190893,1.322175,77062.206205,331.288909,Arizona
13,Glendale,75.822699,424.000000,80.197111,2.010290,159690.979195,219.851930,Arizona
14,Yuma,89.963936,NaN,NaN,NaN,56023.513243,275.588443,Arizona
15,Little Rock,124.150876,403.272727,107.318182,2.269219,113052.336212,334.467534,Arkansas
16,Fayetteville,136.078645,NaN,NaN,NaN,66337.030225,364.645346,Arkansas
17,Fort Smith,113.799440,NaN,NaN,NaN,94551.483600,282.491408,Arkansas
18,Jonesboro,128.053377,NaN,NaN,NaN,65864.722222,358.951702,Arkansas
19,Conway,113.451620,NaN,NaN,NaN,67215.833333,312.372626,Arkansas
20,Los Angeles,81.087951,1019.349057,63.419112,2.631776,348019.742446,220.286297,California
21,San Francisco,64.640986,926.949045,67.745936,2.656458,161101.554825,158.428255,California
22,San Diego,60.451393,361.581967,62.641382,2.627188,89564.365707,145.160327,California
23,Irvine,62.142030,465.813333,56.345761,2.595104,137933.815956,168.017955,California
24,San Jose,81.370193,384.400000,67.045390,2.599932,105589.157907,222.419115,California
25,Denver,96.393579,638.220000,66.386765,2.398287,167341.567033,222.062377,Colorado
26,Aurora,101.436132,176.259259,80.208889,1.639689,86601.809957,251.943943,Colorado
27,Colorado Springs,109.031245,479.000000,81.554545,2.620595,94735.161111,263.506472,Colorado
28,Fort Collins,65.148913,NaN,NaN,NaN,90923.758278,130.824530,Colorado
29,Pueblo,133.108033,NaN,NaN,NaN,55546.181818,356.421142,Colorado
...,...,...,...,...,...,...,...,...
208,Ogden,149.525761,NaN,NaN,NaN,90514.612174,346.195750,Utah
209,St. George,NaN,NaN,NaN,NaN,NaN,NaN,Utah
210,Logan,138.058773,NaN,NaN,NaN,86175.714286,299.186121,Utah
211,Burlington,92.676069,165.400000,71.695500,1.572702,100636.318990,249.731546,Vermont
212,Montpelier,NaN,NaN,NaN,NaN,22350.572222,NaN,Vermont
213,Virginia Beach,69.980373,144.181818,92.608182,2.377143,93877.976447,195.849460,Virginia
214,Norfolk,96.194558,621.600000,69.898000,2.822722,139467.565660,270.941832,Virginia
215,Richmond,112.704521,324.184211,76.794727,2.294704,124285.721706,315.214114,Virginia
216,Hampton,97.878375,NaN,NaN,NaN,47657.257984,271.507662,Virginia
217,Roanoke,84.184330,NaN,NaN,NaN,83955.175659,201.626666,Virginia
218,Seattle,79.723243,942.616438,63.361812,2.543029,120734.853017,195.353594,Washington
219,Tacoma,129.815255,NaN,NaN,NaN,138851.047797,364.745391,Washington
220,Vancouver,93.065338,NaN,NaN,NaN,77988.879630,246.031284,Washington
221,Everett,135.191433,275.600000,64.521500,2.178689,99452.878049,344.729678,Washington
222,Spokane,134.096878,224.578947,75.030000,1.581039,83641.229909,334.870437,Washington
223,Charleston,124.496181,NaN,NaN,NaN,92774.344085,341.583570,West Virginia
224,Huntington,111.211455,NaN,NaN,NaN,47066.776604,256.794242,West Virginia
225,Parkersburg,NaN,NaN,NaN,NaN,NaN,NaN,West Virginia
226,Morgantown,117.756677,NaN,NaN,NaN,48879.100000,267.351905,West Virginia
227,Wheeling,97.567017,NaN,NaN,NaN,58477.240769,240.380868,West Virginia
228,Milwaukee,112.403837,481.125000,85.912092,1.921060,111891.420684,248.796169,Wisconsin
229,Madison,125.285525,195.533333,87.102283,1.619649,104573.191148,303.706252,Wisconsin
230,Waukesha,114.124402,NaN,NaN,NaN,68200.952414,281.617128,Wisconsin
231,Green Bay,92.159108,NaN,NaN,NaN,110269.061224,222.376025,Wisconsin
232,Appleton,89.422308,NaN,NaN,NaN,112723.451613,204.605858,Wisconsin
233,Cheyenne,111.067800,NaN,NaN,NaN,129977.905769,258.143498,Wyoming
234,Casper,118.813999,NaN,NaN,NaN,66967.902381,296.798243,Wyoming
235,Gillette,110.658160,NaN,NaN,NaN,43648.375000,268.584859,Wyoming
236,Laramie,79.391602,NaN,NaN,NaN,39724.100000,179.518493,Wyoming
237,Riverton,130.309810,NaN,NaN,NaN,59840.211111,297.670463,Wyoming