In order to merge our data into one data frame, we needed to have a column to merge on.
The data from NOAA was needed in a special format (City, State, Country). Ex Austin, TX, US
We needed to add the states for each of our cities in the list, so this notebook was made

In [2]:
import pandas as pd
import numpy as np
from city_list import slist, clist

In [29]:
masterlist = pd.DataFrame(clist, columns = ["City"])
masterlist["State"] = slist
masterlist.reset_index()
masterlist

                 City          State
0          Birmingham        Alabama
1              Mobile        Alabama
2          Montgomery        Alabama
3          Huntsville        Alabama
4          Tuscaloosa        Alabama
5           Anchorage         Alaska
6           Fairbanks         Alaska
7              Juneau         Alaska
8              Palmer         Alaska
9             Wasilla         Alaska
10            Phoenix        Arizona
11               Mesa        Arizona
12             Tucson        Arizona
13           Glendale        Arizona
14               Yuma        Arizona
15        Little Rock       Arkansas
16       Fayetteville       Arkansas
17         Fort Smith       Arkansas
18          Jonesboro       Arkansas
19             Conway       Arkansas
20        Los Angeles     California
21      San Francisco     California
22          San Diego     California
23             Irvine     California
24           San Jose     California
25             Denver       Colorado
26             Aurora       Colorado
27   Colorado Springs       Colorado
28       Fort Collins       Colorado
29             Pueblo       Colorado
..                ...            ...
208             Ogden           Utah
209        St. George           Utah
210             Logan           Utah
211        Burlington        Vermont
212        Montpelier        Vermont
213    Virginia Beach       Virginia
214           Norfolk       Virginia
215          Richmond       Virginia
216           Hampton       Virginia
217           Roanoke       Virginia
218           Seattle     Washington
219            Tacoma     Washington
220         Vancouver     Washington
221           Everett     Washington
222           Spokane     Washington
223        Charleston  West Virginia
224        Huntington  West Virginia
225       Parkersburg  West Virginia
226        Morgantown  West Virginia
227          Wheeling  West Virginia
228         Milwaukee      Wisconsin
229           Madison      Wisconsin
230          Waukesha      Wisconsin
231         Green Bay      Wisconsin
232          Appleton      Wisconsin
233          Cheyenne        Wyoming
234            Casper        Wyoming
235          Gillette        Wyoming
236           Laramie        Wyoming
237          Riverton        Wyoming

[238 rows x 2 columns]

A list of US state abbreviations, taken from a good samaritans git hub

In [8]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Palau': 'PW',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

Data Frame

In [40]:
abb = pd.DataFrame([us_state_abbrev]).transpose()
abb= abb.reset_index()
abb.columns = ["State","abbreviation"]
abb

                       State abbreviation
0                    Alabama           AL
1                     Alaska           AK
2                    Arizona           AZ
3                   Arkansas           AR
4                 California           CA
5                   Colorado           CO
6                Connecticut           CT
7                   Delaware           DE
8       District of Columbia           DC
9                    Florida           FL
10                   Georgia           GA
11                    Hawaii           HI
12                     Idaho           ID
13                  Illinois           IL
14                   Indiana           IN
15                      Iowa           IA
16                    Kansas           KS
17                  Kentucky           KY
18                 Louisiana           LA
19                     Maine           ME
20                  Maryland           MD
21             Massachusetts           MA
22                  Michigan           MI
23                 Minnesota           MN
24               Mississippi           MS
25                  Missouri           MO
26                   Montana           MT
27                  Nebraska           NE
28                    Nevada           NV
29             New Hampshire           NH
30                New Jersey           NJ
31                New Mexico           NM
32                  New York           NY
33            North Carolina           NC
34              North Dakota           ND
35  Northern Mariana Islands           MP
36                      Ohio           OH
37                  Oklahoma           OK
38                    Oregon           OR
39                     Palau           PW
40              Pennsylvania           PA
41               Puerto Rico           PR
42              Rhode Island           RI
43            South Carolina           SC
44              South Dakota           SD
45                 Tennessee           TN
46                     Texas           TX
47                      Utah           UT
48                   Vermont           VT
49            Virgin Islands           VI
50                  Virginia           VA
51                Washington           WA
52             West Virginia           WV
53                 Wisconsin           WI
54                   Wyoming           WY

Add in the state to each city in our list

In [41]:
df3 = pd.merge(masterlist,abb,on="State")
df3

                 City          State abbreviation
0          Birmingham        Alabama           AL
1              Mobile        Alabama           AL
2          Montgomery        Alabama           AL
3          Huntsville        Alabama           AL
4          Tuscaloosa        Alabama           AL
5           Anchorage         Alaska           AK
6           Fairbanks         Alaska           AK
7              Juneau         Alaska           AK
8              Palmer         Alaska           AK
9             Wasilla         Alaska           AK
10            Phoenix        Arizona           AZ
11               Mesa        Arizona           AZ
12             Tucson        Arizona           AZ
13           Glendale        Arizona           AZ
14               Yuma        Arizona           AZ
15        Little Rock       Arkansas           AR
16       Fayetteville       Arkansas           AR
17         Fort Smith       Arkansas           AR
18          Jonesboro       Arkansas           AR
19             Conway       Arkansas           AR
20        Los Angeles     California           CA
21      San Francisco     California           CA
22          San Diego     California           CA
23             Irvine     California           CA
24           San Jose     California           CA
25             Denver       Colorado           CO
26             Aurora       Colorado           CO
27   Colorado Springs       Colorado           CO
28       Fort Collins       Colorado           CO
29             Pueblo       Colorado           CO
..                ...            ...          ...
208             Ogden           Utah           UT
209        St. George           Utah           UT
210             Logan           Utah           UT
211        Burlington        Vermont           VT
212        Montpelier        Vermont           VT
213    Virginia Beach       Virginia           VA
214           Norfolk       Virginia           VA
215          Richmond       Virginia           VA
216           Hampton       Virginia           VA
217           Roanoke       Virginia           VA
218           Seattle     Washington           WA
219            Tacoma     Washington           WA
220         Vancouver     Washington           WA
221           Everett     Washington           WA
222           Spokane     Washington           WA
223        Charleston  West Virginia           WV
224        Huntington  West Virginia           WV
225       Parkersburg  West Virginia           WV
226        Morgantown  West Virginia           WV
227          Wheeling  West Virginia           WV
228         Milwaukee      Wisconsin           WI
229           Madison      Wisconsin           WI
230          Waukesha      Wisconsin           WI
231         Green Bay      Wisconsin           WI
232          Appleton      Wisconsin           WI
233          Cheyenne        Wyoming           WY
234            Casper        Wyoming           WY
235          Gillette        Wyoming           WY
236           Laramie        Wyoming           WY
237          Riverton        Wyoming           WY

[238 rows x 3 columns]

Not used

In [44]:
print(list(df3["abbreviation"]))

['AL', 'AL', 'AL', 'AL', 'AL', 'AK', 'AK', 'AK', 'AK', 'AK', 'AZ', 'AZ', 'AZ', 'AZ', 'AZ', 'AR', 'AR', 'AR', 'AR', 'AR', 'CA', 'CA', 'CA', 'CA', 'CA', 'CO', 'CO', 'CO', 'CO', 'CO', 'CT', 'CT', 'CT', 'CT', 'CT', 'DE', 'DE', 'DC', 'FL', 'FL', 'FL', 'FL', 'FL', 'GA', 'GA', 'GA', 'GA', 'GA', 'HI', 'HI', 'HI', 'HI', 'HI', 'ID', 'ID', 'ID', 'ID', 'ID', 'IL', 'IL', 'IL', 'IL', 'IL', 'IN', 'IN', 'IN', 'IN', 'IN', 'IA', 'IA', 'IA', 'IA', 'IA', 'KS', 'KS', 'KS', 'KS', 'KS', 'KY', 'KY', 'KY', 'KY', 'KY', 'LA', 'LA', 'LA', 'LA', 'LA', 'ME', 'ME', 'ME', 'ME', 'ME', 'MD', 'MD', 'MD', 'MD', 'MD', 'MA', 'MA', 'MA', 'MA', 'MA', 'MI', 'MI', 'MI', 'MI', 'MI', 'MN', 'MN', 'MN', 'MN', 'MN', 'MS', 'MS', 'MS', 'MS', 'MS', 'MO', 'MO', 'MO', 'MO', 'MO', 'MT', 'MT', 'MT', 'MT', 'MT', 'NE', 'NE', 'NE', 'NE', 'NE', 'NV', 'NV', 'NV', 'NV', 'NV', 'NH', 'NH', 'NJ', 'NJ', 'NJ', 'NJ', 'NM', 'NM', 'NM', 'NM', 'NM', 'NY', 'NY', 'NY', 'NY', 'NY', 'NC', 'NC', 'NC', 'NC', 'NC', 'ND', 'ND', 'ND', 'ND', 'ND', 'OH', 'OH', 'OH', 'OH', 'OH', 'OK', 'OK', 'OK', 'OK', 'OK', 'OR', 'OR', 'OR', 'OR', 'OR', 'PA', 'PA', 'PA', 'PA', 'PA', 'RI', 'RI', 'SC', 'SC', 'SC', 'SC', 'SC', 'SD', 'SD', 'SD', 'SD', 'SD', 'TN', 'TN', 'TN', 'TN', 'TN', 'TX', 'TX', 'TX', 'TX', 'TX', 'UT', 'UT', 'UT', 'UT', 'UT', 'VT', 'VT', 'VA', 'VA', 'VA', 'VA', 'VA', 'WA', 'WA', 'WA', 'WA', 'WA', 'WV', 'WV', 'WV', 'WV', 'WV', 'WI', 'WI', 'WI', 'WI', 'WI', 'WY', 'WY', 'WY', 'WY', 'WY']

In [ ]:
# thank you to @kinghelix and @trevormarburger for this idea
abbrev_us_state = dict(map(reversed, us_state_abbrev.items()))

# Simple test examples
if __name__ == '__main__':
    print("Wisconin --> WI?", us_state_abbrev['Wisconsin'] == 'WI')
    print("WI --> Wisconin?", abbrev_us_state['WI'] == 'Wisconsin')