In [69]:
import json
import requests
import pandas as pd
from config import api_key
from city_list import clist,alist

## Find city id based on name

In [31]:
base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/locations"
params = {
    "locationcategoryid":"City",
    "limit":"1000",
    "offset":"1001"
}
headers = {
    "token": api_key
}
response = requests.get(base_url, params=params,headers=headers)
response.json()

{'metadata': {'resultset': {'offset': 1001, 'count': 1987, 'limit': 1000}},
 'results': [{'mindate': '2003-11-01',
   'maxdate': '2019-09-02',
   'name': 'Mus, TU',
   'datacoverage': 0.9973,
   'id': 'CITY:TU000042'},
  {'mindate': '2003-11-01',
   'maxdate': '2019-09-02',
   'name': 'Nevsehir, TU',
   'datacoverage': 1,
   'id': 'CITY:TU000043'},
  {'mindate': '2001-07-01',
   'maxdate': '2019-09-02',
   'name': 'Nigde, TU',
   'datacoverage': 0.9999,
   'id': 'CITY:TU000044'},
  {'mindate': '1927-03-01',
   'maxdate': '2019-09-02',
   'name': 'Rize, TU',
   'datacoverage': 1,
   'id': 'CITY:TU000046'},
  {'mindate': '2003-11-01',
   'maxdate': '2019-09-02',
   'name': 'Sakarya, TU',
   'datacoverage': 0.9986,
   'id': 'CITY:TU000047'},
  {'mindate': '1951-05-08',
   'maxdate': '2019-09-02',
   'name': 'Samsun, TU',
   'datacoverage': 0.9986,
   'id': 'CITY:TU000048'},
  {'mindate': '1963-01-01',
   'maxdate': '2019-09-02',
   'name': 'Siirt, TU',
   'datacoverage': 0.9993,
   'id': 'CITY:TU000049'},
  {'mindate': '1929-02-01',
   'maxdate': '2019-09-02',
   'name': 'Sivas, TU',
   'datacoverage': 0.9838,
   'id': 'CITY:TU000050'},
  {'mindate': '1963-01-01',
   'maxdate': '2019-09-02',
   'name': 'Tekirdag, TU',
   'datacoverage': 1,
   'id': 'CITY:TU000051'},
  {'mindate': '2002-03-01',
   'maxdate': '2019-09-02',
   'name': 'Tokat, TU',
   'datacoverage': 0.9998,
   'id': 'CITY:TU000052'},
  {'mindate': '1963-01-01',
   'maxdate': '2019-09-02',
   'name': 'Usak, TU',
   'datacoverage': 0.9819,
   'id': 'CITY:TU000054'},
  {'mindate': '1938-05-01',
   'maxdate': '2019-09-02',
   'name': 'Van, TU',
   'datacoverage': 0.9968,
   'id': 'CITY:TU000055'},
  {'mindate': '1998-02-01',
   'maxdate': '2019-09-02',
   'name': 'Yozgat, TU',
   'datacoverage': 0.9993,
   'id': 'CITY:TU000056'},
  {'mindate': '1957-07-01',
   'maxdate': '2019-09-02',
   'name': 'Zonguldak, TU',
   'datacoverage': 1,
   'id': 'CITY:TU000057'},
  {'mindate': '1898-07-01',
   'maxdate': '2019-09-02',
   'name': 'Ashgabat, TX',
   'datacoverage': 0.942,
   'id': 'CITY:TX000001'},
  {'mindate': '1959-01-01',
   'maxdate': '1991-06-30',
   'name': 'Mary, TX',
   'datacoverage': 0.9412,
   'id': 'CITY:TX000002'},
  {'mindate': '1933-01-01',
   'maxdate': '2019-09-02',
   'name': 'Turkmenbashi, TX',
   'datacoverage': 0.9709,
   'id': 'CITY:TX000003'},
  {'mindate': '1959-02-01',
   'maxdate': '1989-12-31',
   'name': 'Arusha, TZ',
   'datacoverage': 1,
   'id': 'CITY:TZ000001'},
  {'mindate': '1950-01-01',
   'maxdate': '1989-12-31',
   'name': 'Bukoba, TZ',
   'datacoverage': 0.9979,
   'id': 'CITY:TZ000002'},
  {'mindate': '1957-01-01',
   'maxdate': '2019-09-02',
   'name': 'Dar es Salaam, TZ',
   'datacoverage': 0.9994,
   'id': 'CITY:TZ000003'},
  {'mindate': '1957-01-01',
   'maxdate': '2019-09-02',
   'name': 'Dodoma, TZ',
   'datacoverage': 1,
   'id': 'CITY:TZ000004'},
  {'mindate': '1960-01-01',
   'maxdate': '1990-03-31',
   'name': 'Iringa, TZ',
   'datacoverage': 1,
   'id': 'CITY:TZ000005'},
  {'mindate': '1950-01-01',
   'maxdate': '1989-12-31',
   'name': 'Moshi, TZ',
   'datacoverage': 1,
   'id': 'CITY:TZ000009'},
  {'mindate': '1957-01-01',
   'maxdate': '2019-09-02',
   'name': 'Mtwara, TZ',
   'datacoverage': 0.9993,
   'id': 'CITY:TZ000010'},
  {'mindate': '1950-01-01',
   'maxdate': '1989-12-31',
   'name': 'Musoma, TZ',
   'datacoverage': 1,
   'id': 'CITY:TZ000011'},
  {'mindate': '1950-01-01',
   'maxdate': '2019-09-02',
   'name': 'Mwanza, TZ',
   'datacoverage': 0.9993,
   'id': 'CITY:TZ000012'},
  {'mindate': '1957-01-01',
   'maxdate': '2019-09-02',
   'name': 'Songea, TZ',
   'datacoverage': 0.9819,
   'id': 'CITY:TZ000015'},
  {'mindate': '1951-08-01',
   'maxdate': '2019-09-02',
   'name': 'Tabora, TZ',
   'datacoverage': 1,
   'id': 'CITY:TZ000017'},
  {'mindate': '1957-01-01',
   'maxdate': '2019-09-02',
   'name': 'Zanzibar, TZ',
   'datacoverage': 0.8016,
   'id': 'CITY:TZ000019'},
  {'mindate': '1971-04-01',
   'maxdate': '1976-12-31',
   'name': 'Arua, UG',
   'datacoverage': 0.9567,
   'id': 'CITY:UG000001'},
  {'mindate': '1926-01-01',
   'maxdate': '1986-12-15',
   'name': 'Gulu, UG',
   'datacoverage': 0.9727,
   'id': 'CITY:UG000002'},
  {'mindate': '1955-01-01',
   'maxdate': '1986-12-30',
   'name': 'Jinja, UG',
   'datacoverage': 0.9609,
   'id': 'CITY:UG000003'},
  {'mindate': '1939-08-01',
   'maxdate': '2019-09-02',
   'name': 'Belfast, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000001'},
  {'mindate': '1880-12-01',
   'maxdate': '2017-12-31',
   'name': 'Birmingham, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000002'},
  {'mindate': '1959-12-31',
   'maxdate': '2019-09-02',
   'name': 'Dundee, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000004'},
  {'mindate': '1959-12-31',
   'maxdate': '2017-12-31',
   'name': 'Edinburgh, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000005'},
  {'mindate': '1914-01-01',
   'maxdate': '2017-12-31',
   'name': 'Glasgow, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000006'},
  {'mindate': '1910-12-31',
   'maxdate': '2017-12-31',
   'name': 'Leeds, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000007'},
  {'mindate': '1920-12-31',
   'maxdate': '2004-12-31',
   'name': 'Liverpool, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000008'},
  {'mindate': '1904-02-01',
   'maxdate': '2019-09-02',
   'name': 'London, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000009'},
  {'mindate': '1973-01-01',
   'maxdate': '2019-09-02',
   'name': 'Manchester, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000010'},
  {'mindate': '1882-12-31',
   'maxdate': '2017-12-31',
   'name': 'Sheffield, UK',
   'datacoverage': 0.9846,
   'id': 'CITY:UK000011'},
  {'mindate': '1959-12-31',
   'maxdate': '2012-12-31',
   'name': 'Southampton, UK',
   'datacoverage': 1,
   'id': 'CITY:UK000012'},
  {'mindate': '1936-01-01',
   'maxdate': '2009-06-17',
   'name': 'Cherkasy, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000001'},
  {'mindate': '1936-01-01',
   'maxdate': '2009-06-17',
   'name': 'Chernihiv, UP',
   'datacoverage': 0.9819,
   'id': 'CITY:UP000002'},
  {'mindate': '1941-03-01',
   'maxdate': '2019-09-02',
   'name': 'Chernivtsi, UP',
   'datacoverage': 0.96,
   'id': 'CITY:UP000003'},
  {'mindate': '1936-12-01',
   'maxdate': '2019-09-02',
   'name': "Dnipropetrovs'k, UP",
   'datacoverage': 1,
   'id': 'CITY:UP000004'},
  {'mindate': '1949-07-01',
   'maxdate': '2014-05-01',
   'name': "Donets'k, UP",
   'datacoverage': 1,
   'id': 'CITY:UP000005'},
  {'mindate': '1941-01-01',
   'maxdate': '2014-02-01',
   'name': "Ivano-frankivs'k, UP",
   'datacoverage': 1,
   'id': 'CITY:UP000006'},
  {'mindate': '1936-01-01',
   'maxdate': '2019-09-02',
   'name': 'Kharkiv, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000007'},
  {'mindate': '1879-02-01',
   'maxdate': '2019-09-02',
   'name': 'Kherson, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000008'},
  {'mindate': '1955-01-01',
   'maxdate': '2019-09-02',
   'name': "Khmel'nyts'kyz, UP",
   'datacoverage': 1,
   'id': 'CITY:UP000009'},
  {'mindate': '1949-07-31',
   'maxdate': '2019-09-02',
   'name': 'Kirovohrad, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000010'},
  {'mindate': '1959-07-01',
   'maxdate': '2009-06-17',
   'name': "Kovel', UP",
   'datacoverage': 1,
   'id': 'CITY:UP000011'},
  {'mindate': '1881-01-01',
   'maxdate': '2019-09-02',
   'name': 'Kyiv, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000012'},
  {'mindate': '1936-01-01',
   'maxdate': '2019-09-02',
   'name': "L'viv, UP",
   'datacoverage': 1,
   'id': 'CITY:UP000013'},
  {'mindate': '1881-01-01',
   'maxdate': '2014-07-06',
   'name': "Luhans'k, UP",
   'datacoverage': 0.9949,
   'id': 'CITY:UP000014'},
  {'mindate': '1881-01-01',
   'maxdate': '2012-12-31',
   'name': 'Mykolayiv, UP',
   'datacoverage': 0.9832,
   'id': 'CITY:UP000015'},
  {'mindate': '1894-01-01',
   'maxdate': '2019-09-02',
   'name': 'Odesa, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000016'},
  {'mindate': '1900-01-01',
   'maxdate': '2019-09-02',
   'name': 'Poltava, UP',
   'datacoverage': 0.9821,
   'id': 'CITY:UP000017'},
  {'mindate': '1959-01-01',
   'maxdate': '2019-09-02',
   'name': 'Rivne, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000018'},
  {'mindate': '1959-07-01',
   'maxdate': '2009-06-17',
   'name': "Simferopol', UP",
   'datacoverage': 1,
   'id': 'CITY:UP000019'},
  {'mindate': '1936-01-01',
   'maxdate': '2019-09-02',
   'name': 'Sumy, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000020'},
  {'mindate': '1944-05-01',
   'maxdate': '2019-09-02',
   'name': "Ternopil', UP",
   'datacoverage': 1,
   'id': 'CITY:UP000021'},
  {'mindate': '1946-05-01',
   'maxdate': '2019-09-02',
   'name': 'Uzhhorod, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000022'},
  {'mindate': '1936-01-01',
   'maxdate': '2019-09-02',
   'name': 'Vinnytsya, UP',
   'datacoverage': 0.9917,
   'id': 'CITY:UP000023'},
  {'mindate': '1936-01-01',
   'maxdate': '2009-06-17',
   'name': 'Zaporiyhzhya, UP',
   'datacoverage': 1,
   'id': 'CITY:UP000024'},
  {'mindate': '1938-01-01',
   'maxdate': '2019-09-02',
   'name': 'Zhytomyra, UP',
   'datacoverage': 0.9723,
   'id': 'CITY:UP000025'},
  {'mindate': '1870-11-01',
   'maxdate': '2019-09-06',
   'name': 'Washington D.C., US',
   'datacoverage': 1,
   'id': 'CITY:US000001'},
  {'mindate': '1895-11-01',
   'maxdate': '2019-09-06',
   'name': 'Alexander City, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010001'},
  {'mindate': '1903-02-01',
   'maxdate': '2019-09-06',
   'name': 'Anniston, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010002'},
  {'mindate': '1906-04-01',
   'maxdate': '2019-09-06',
   'name': 'Auburn, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010003'},
  {'mindate': '1900-10-01',
   'maxdate': '2019-09-06',
   'name': 'Birmingham, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010004'},
  {'mindate': '1907-08-01',
   'maxdate': '2019-09-05',
   'name': 'Cullman, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010005'},
  {'mindate': '1931-01-01',
   'maxdate': '2019-09-06',
   'name': 'Dothan, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010006'},
  {'mindate': '1902-05-01',
   'maxdate': '2019-09-06',
   'name': 'Enterprise, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010007'},
  {'mindate': '1892-06-01',
   'maxdate': '2019-09-05',
   'name': 'Eufaula, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010008'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Florence, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010009'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Fort Payne, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010010'},
  {'mindate': '1893-07-01',
   'maxdate': '2019-09-06',
   'name': 'Gadsden, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010011'},
  {'mindate': '1894-02-01',
   'maxdate': '2019-09-06',
   'name': 'Huntsville, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010012'},
  {'mindate': '1891-10-01',
   'maxdate': '2019-09-06',
   'name': 'Jasper, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010013'},
  {'mindate': '1931-01-01',
   'maxdate': '2019-09-06',
   'name': 'Mobile, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010014'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Montgomery, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010015'},
  {'mindate': '1895-01-01',
   'maxdate': '2019-09-05',
   'name': 'Selma, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010016'},
  {'mindate': '1888-02-01',
   'maxdate': '2019-09-05',
   'name': 'Talladega, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010017'},
  {'mindate': '1908-06-01',
   'maxdate': '2019-09-06',
   'name': 'Troy, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010018'},
  {'mindate': '1900-01-01',
   'maxdate': '2019-09-06',
   'name': 'Tuscaloosa, AL US',
   'datacoverage': 1,
   'id': 'CITY:US010019'},
  {'mindate': '1916-02-01',
   'maxdate': '2019-09-06',
   'name': 'Anchorage, AK US',
   'datacoverage': 1,
   'id': 'CITY:US020001'},
  {'mindate': '1904-09-01',
   'maxdate': '2019-09-06',
   'name': 'Fairbanks, AK US',
   'datacoverage': 1,
   'id': 'CITY:US020002'},
  {'mindate': '1915-11-01',
   'maxdate': '2019-09-06',
   'name': 'Juneau, AK US',
   'datacoverage': 1,
   'id': 'CITY:US020003'},
  {'mindate': '1908-01-01',
   'maxdate': '2019-09-06',
   'name': 'Nome, AK US',
   'datacoverage': 1,
   'id': 'CITY:US020004'},
  {'mindate': '1922-01-01',
   'maxdate': '2019-09-06',
   'name': 'Seward, AK US',
   'datacoverage': 1,
   'id': 'CITY:US020005'},
  {'mindate': '1948-03-01',
   'maxdate': '2019-09-06',
   'name': 'Bullhead City, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040001'},
  {'mindate': '1898-06-01',
   'maxdate': '2019-09-06',
   'name': 'Casa Grande, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040002'},
  {'mindate': '1903-12-01',
   'maxdate': '2019-09-06',
   'name': 'Douglas, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040003'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Flagstaff, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040004'},
  {'mindate': '1916-06-01',
   'maxdate': '2019-09-05',
   'name': 'Green Valley, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040005'},
  {'mindate': '1901-05-12',
   'maxdate': '2019-09-06',
   'name': 'Kingman, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040006'},
  {'mindate': '1967-09-01',
   'maxdate': '2019-09-05',
   'name': 'Lake Havasu City, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040007'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Mesa, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040008'},
  {'mindate': '1892-12-01',
   'maxdate': '2019-09-06',
   'name': 'Nogales, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040009'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Payson, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040010'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Phoenix, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040011'},
  {'mindate': '1898-05-01',
   'maxdate': '2019-09-06',
   'name': 'Prescott, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040012'},
  {'mindate': '1900-02-01',
   'maxdate': '2019-09-06',
   'name': 'Sierra Vista, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040013'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Tucson, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040014'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Yuma, AZ US',
   'datacoverage': 1,
   'id': 'CITY:US040015'},
  {'mindate': '1891-03-01',
   'maxdate': '2019-09-06',
   'name': 'Arkadelphia, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050001'},
  {'mindate': '1892-01-01',
   'maxdate': '2019-09-06',
   'name': 'Blytheville, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050002'},
  {'mindate': '1886-01-01',
   'maxdate': '2019-09-06',
   'name': 'Camden, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050003'},
  {'mindate': '1890-08-01',
   'maxdate': '2019-09-05',
   'name': 'Conway, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050004'},
  {'mindate': '1931-01-01',
   'maxdate': '2019-09-06',
   'name': 'El Dorado, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050005'},
  {'mindate': '1892-01-01',
   'maxdate': '2019-09-06',
   'name': 'Fayetteville, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050006'},
  {'mindate': '1892-01-01',
   'maxdate': '2019-09-05',
   'name': 'Forrest City, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050007'},
  {'mindate': '1900-10-01',
   'maxdate': '2019-09-06',
   'name': 'Fort Smith, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050008'},
  {'mindate': '1891-11-01',
   'maxdate': '2019-09-06',
   'name': 'Harrison, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050009'},
  {'mindate': '1890-05-01',
   'maxdate': '2019-09-05',
   'name': 'Hope, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050010'},
  {'mindate': '1875-08-01',
   'maxdate': '2019-09-06',
   'name': 'Hot Springs, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050011'},
  {'mindate': '1896-02-12',
   'maxdate': '2019-09-06',
   'name': 'Jonesboro, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050012'},
  {'mindate': '1874-06-01',
   'maxdate': '2019-09-06',
   'name': 'Little Rock, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050013'},
  {'mindate': '1931-01-01',
   'maxdate': '2019-09-05',
   'name': 'Magnolia, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050014'},
  {'mindate': '1902-03-03',
   'maxdate': '2019-09-06',
   'name': 'Mountain Home, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050015'},
  {'mindate': '1892-01-01',
   'maxdate': '2019-09-05',
   'name': 'Paragould, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050016'},
  {'mindate': '1884-05-01',
   'maxdate': '2019-09-06',
   'name': 'Pine Bluff, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050017'},
  {'mindate': '1886-06-01',
   'maxdate': '2019-09-06',
   'name': 'Russellville, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050018'},
  {'mindate': '1892-09-01',
   'maxdate': '2019-09-06',
   'name': 'Searcy, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050019'},
  {'mindate': '1916-09-01',
   'maxdate': '2019-09-06',
   'name': 'Siloam Springs, AR US',
   'datacoverage': 1,
   'id': 'CITY:US050020'},
  {'mindate': '1902-01-01',
   'maxdate': '2019-09-06',
   'name': 'Anaheim, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060001'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Bakersfield, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060002'},
  {'mindate': '1903-01-01',
   'maxdate': '2019-09-06',
   'name': 'Barstow, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060003'},
  {'mindate': '1913-01-01',
   'maxdate': '2019-09-06',
   'name': 'Blythe, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060004'},
  {'mindate': '1906-01-01',
   'maxdate': '2019-09-06',
   'name': 'Chico, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060005'},
  {'mindate': '1911-07-01',
   'maxdate': '2019-09-05',
   'name': 'Clearlake, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060006'},
  {'mindate': '1911-09-01',
   'maxdate': '2019-09-05',
   'name': 'Coalinga, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060007'},
  {'mindate': '1901-11-01',
   'maxdate': '2019-09-06',
   'name': 'El Centro, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060008'},
  {'mindate': '1931-01-01',
   'maxdate': '2019-09-06',
   'name': 'Eureka, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060009'},
  {'mindate': '1912-08-01',
   'maxdate': '2019-09-06',
   'name': 'Fresno, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060010'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Grass Valley, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060011'},
  {'mindate': '1906-03-01',
   'maxdate': '2019-09-06',
   'name': 'Long Beach, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060012'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Los Angeles, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060013'},
  {'mindate': '1899-06-01',
   'maxdate': '2019-09-06',
   'name': 'Merced, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060014'},
  {'mindate': '1899-06-01',
   'maxdate': '2019-09-06',
   'name': 'Modesto, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060015'},
  {'mindate': '1906-03-01',
   'maxdate': '2019-09-06',
   'name': 'Monterey, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060016'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Napa, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060017'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Oakland, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060018'},
  {'mindate': '1893-01-01',
   'maxdate': '2019-09-06',
   'name': 'Oceanside, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060019'},
  {'mindate': '1894-05-01',
   'maxdate': '2019-09-06',
   'name': 'Oxnard, CA US',
   'datacoverage': 1,
   'id': 'CITY:US060020'},

In [32]:
response_json = response.json()
df = pd.DataFrame(response_json["results"])
df.head()

   datacoverage             id     maxdate     mindate          name
0        0.9973  CITY:TU000042  2019-09-02  2003-11-01       Mus, TU
1        1.0000  CITY:TU000043  2019-09-02  2003-11-01  Nevsehir, TU
2        0.9999  CITY:TU000044  2019-09-02  2001-07-01     Nigde, TU
3        1.0000  CITY:TU000046  2019-09-02  1927-03-01      Rize, TU
4        0.9986  CITY:TU000047  2019-09-02  2003-11-01   Sakarya, TU

In [73]:
city_df = pd.DataFrame(clist, columns=["city"])
city_df["state"]=alist
city_df["lookup"]=city_df["city"]+", "+city_df["state"]+" US"
city_df

                 city state                   lookup
0          Birmingham    AL        Birmingham, AL US
1              Mobile    AL            Mobile, AL US
2          Montgomery    AL        Montgomery, AL US
3          Huntsville    AL        Huntsville, AL US
4          Tuscaloosa    AL        Tuscaloosa, AL US
5           Anchorage    AK         Anchorage, AK US
6           Fairbanks    AK         Fairbanks, AK US
7              Juneau    AK            Juneau, AK US
8              Palmer    AK            Palmer, AK US
9             Wasilla    AK           Wasilla, AK US
10            Phoenix    AZ           Phoenix, AZ US
11               Mesa    AZ              Mesa, AZ US
12             Tucson    AZ            Tucson, AZ US
13           Glendale    AZ          Glendale, AZ US
14               Yuma    AZ              Yuma, AZ US
15        Little Rock    AR       Little Rock, AR US
16       Fayetteville    AR      Fayetteville, AR US
17         Fort Smith    AR        Fort Smith, AR US
18          Jonesboro    AR         Jonesboro, AR US
19             Conway    AR            Conway, AR US
20        Los Angeles    CA       Los Angeles, CA US
21      San Francisco    CA     San Francisco, CA US
22          San Diego    CA         San Diego, CA US
23             Irvine    CA            Irvine, CA US
24           San Jose    CA          San Jose, CA US
25             Denver    CO            Denver, CO US
26             Aurora    CO            Aurora, CO US
27   Colorado Springs    CO  Colorado Springs, CO US
28       Fort Collins    CO      Fort Collins, CO US
29             Pueblo    CO            Pueblo, CO US
..                ...   ...                      ...
208             Ogden    UT             Ogden, UT US
209        St. George    UT        St. George, UT US
210             Logan    UT             Logan, UT US
211        Burlington    VT        Burlington, VT US
212        Montpelier    VT        Montpelier, VT US
213    Virginia Beach    VA    Virginia Beach, VA US
214           Norfolk    VA           Norfolk, VA US
215          Richmond    VA          Richmond, VA US
216           Hampton    VA           Hampton, VA US
217           Roanoke    VA           Roanoke, VA US
218           Seattle    WA           Seattle, WA US
219            Tacoma    WA            Tacoma, WA US
220         Vancouver    WA         Vancouver, WA US
221           Everett    WA           Everett, WA US
222           Spokane    WA           Spokane, WA US
223        Charleston    WV        Charleston, WV US
224        Huntington    WV        Huntington, WV US
225       Parkersburg    WV       Parkersburg, WV US
226        Morgantown    WV        Morgantown, WV US
227          Wheeling    WV          Wheeling, WV US
228         Milwaukee    WI         Milwaukee, WI US
229           Madison    WI           Madison, WI US
230          Waukesha    WI          Waukesha, WI US
231         Green Bay    WI         Green Bay, WI US
232          Appleton    WI          Appleton, WI US
233          Cheyenne    WY          Cheyenne, WY US
234            Casper    WY            Casper, WY US
235          Gillette    WY          Gillette, WY US
236           Laramie    WY           Laramie, WY US
237          Riverton    WY          Riverton, WY US

[238 rows x 3 columns]

In [38]:
df_ids = df[["id","name"]]
df_ids.head()

              id          name
0  CITY:TU000042       Mus, TU
1  CITY:TU000043  Nevsehir, TU
2  CITY:TU000044     Nigde, TU
3  CITY:TU000046      Rize, TU
4  CITY:TU000047   Sakarya, TU

## Need to loop through locations

In [74]:
cities = city_df["lookup"]
cities

0            Birmingham, AL US
1                Mobile, AL US
2            Montgomery, AL US
3            Huntsville, AL US
4            Tuscaloosa, AL US
5             Anchorage, AK US
6             Fairbanks, AK US
7                Juneau, AK US
8                Palmer, AK US
9               Wasilla, AK US
10              Phoenix, AZ US
11                 Mesa, AZ US
12               Tucson, AZ US
13             Glendale, AZ US
14                 Yuma, AZ US
15          Little Rock, AR US
16         Fayetteville, AR US
17           Fort Smith, AR US
18            Jonesboro, AR US
19               Conway, AR US
20          Los Angeles, CA US
21        San Francisco, CA US
22            San Diego, CA US
23               Irvine, CA US
24             San Jose, CA US
25               Denver, CO US
26               Aurora, CO US
27     Colorado Springs, CO US
28         Fort Collins, CO US
29               Pueblo, CO US
                ...
208               Ogden, UT US
209          St. George, UT US
210               Logan, UT US
211          Burlington, VT US
212          Montpelier, VT US
213      Virginia Beach, VA US
214             Norfolk, VA US
215            Richmond, VA US
216             Hampton, VA US
217             Roanoke, VA US
218             Seattle, WA US
219              Tacoma, WA US
220           Vancouver, WA US
221             Everett, WA US
222             Spokane, WA US
223          Charleston, WV US
224          Huntington, WV US
225         Parkersburg, WV US
226          Morgantown, WV US
227            Wheeling, WV US
228           Milwaukee, WI US
229             Madison, WI US
230            Waukesha, WI US
231           Green Bay, WI US
232            Appleton, WI US
233            Cheyenne, WY US
234              Casper, WY US
235            Gillette, WY US
236             Laramie, WY US
237            Riverton, WY US
Name: lookup, Length: 238, dtype: object

In [75]:
df_our_cities = df_ids[df_ids["name"].isin(cities)]
df_our_cities

                id                     name
72   CITY:US010004        Birmingham, AL US
80   CITY:US010012        Huntsville, AL US
82   CITY:US010014            Mobile, AL US
83   CITY:US010015        Montgomery, AL US
87   CITY:US010019        Tuscaloosa, AL US
88   CITY:US020001         Anchorage, AK US
89   CITY:US020002         Fairbanks, AK US
90   CITY:US020003            Juneau, AK US
100  CITY:US040008              Mesa, AZ US
103  CITY:US040011           Phoenix, AZ US
106  CITY:US040014            Tucson, AZ US
107  CITY:US040015              Yuma, AZ US
111  CITY:US050004            Conway, AR US
113  CITY:US050006      Fayetteville, AR US
115  CITY:US050008        Fort Smith, AR US
119  CITY:US050012         Jonesboro, AR US
120  CITY:US050013       Little Rock, AR US
140  CITY:US060013       Los Angeles, CA US
157  CITY:US060030         San Diego, CA US
158  CITY:US060031     San Francisco, CA US
159  CITY:US060032          San Jose, CA US
178  CITY:US080003  Colorado Springs, CO US
179  CITY:US080004            Denver, CO US
181  CITY:US080006      Fort Collins, CO US
185  CITY:US080010            Pueblo, CO US
187  CITY:US090001        Bridgeport, CT US
189  CITY:US090003          Hartford, CT US
190  CITY:US090004         New Haven, CT US
194  CITY:US090008          Stamford, CT US
196  CITY:US090010         Waterbury, CT US
..             ...                      ...
816  CITY:US480057       San Antonio, TX US
832  CITY:US490003             Logan, UT US
833  CITY:US490004             Ogden, UT US
834  CITY:US490005             Provo, UT US
835  CITY:US490006    Salt Lake City, UT US
836  CITY:US490007        St. George, UT US
837  CITY:US500001        Burlington, VT US
838  CITY:US500002        Montpelier, VT US
848  CITY:US510009           Hampton, VA US
853  CITY:US510014           Norfolk, VA US
854  CITY:US510015          Richmond, VA US
855  CITY:US510016           Roanoke, VA US
856  CITY:US510017    Virginia Beach, VA US
865  CITY:US530008           Everett, WA US
875  CITY:US530018           Seattle, WA US
876  CITY:US530019           Spokane, WA US
878  CITY:US530021            Tacoma, WA US
879  CITY:US530022         Vancouver, WA US
885  CITY:US540003        Charleston, WV US
887  CITY:US540005        Huntington, WV US
889  CITY:US540007        Morgantown, WV US
890  CITY:US540008       Parkersburg, WV US
891  CITY:US540009          Wheeling, WV US
893  CITY:US550002         Green Bay, WI US
897  CITY:US550006           Madison, WI US
900  CITY:US550009         Milwaukee, WI US
906  CITY:US560001            Casper, WY US
907  CITY:US560002          Cheyenne, WY US
909  CITY:US560004          Gillette, WY US
910  CITY:US560005           Laramie, WY US

[208 rows x 2 columns]

In [76]:
df_index = df_our_cities.set_index("name")
df_index

                                    id
name
Birmingham, AL US        CITY:US010004
Huntsville, AL US        CITY:US010012
Mobile, AL US            CITY:US010014
Montgomery, AL US        CITY:US010015
Tuscaloosa, AL US        CITY:US010019
Anchorage, AK US         CITY:US020001
Fairbanks, AK US         CITY:US020002
Juneau, AK US            CITY:US020003
Mesa, AZ US              CITY:US040008
Phoenix, AZ US           CITY:US040011
Tucson, AZ US            CITY:US040014
Yuma, AZ US              CITY:US040015
Conway, AR US            CITY:US050004
Fayetteville, AR US      CITY:US050006
Fort Smith, AR US        CITY:US050008
Jonesboro, AR US         CITY:US050012
Little Rock, AR US       CITY:US050013
Los Angeles, CA US       CITY:US060013
San Diego, CA US         CITY:US060030
San Francisco, CA US     CITY:US060031
San Jose, CA US          CITY:US060032
Colorado Springs, CO US  CITY:US080003
Denver, CO US            CITY:US080004
Fort Collins, CO US      CITY:US080006
Pueblo, CO US            CITY:US080010
Bridgeport, CT US        CITY:US090001
Hartford, CT US          CITY:US090003
New Haven, CT US         CITY:US090004
Stamford, CT US          CITY:US090008
Waterbury, CT US         CITY:US090010
...                                ...
San Antonio, TX US       CITY:US480057
Logan, UT US             CITY:US490003
Ogden, UT US             CITY:US490004
Provo, UT US             CITY:US490005
Salt Lake City, UT US    CITY:US490006
St. George, UT US        CITY:US490007
Burlington, VT US        CITY:US500001
Montpelier, VT US        CITY:US500002
Hampton, VA US           CITY:US510009
Norfolk, VA US           CITY:US510014
Richmond, VA US          CITY:US510015
Roanoke, VA US           CITY:US510016
Virginia Beach, VA US    CITY:US510017
Everett, WA US           CITY:US530008
Seattle, WA US           CITY:US530018
Spokane, WA US           CITY:US530019
Tacoma, WA US            CITY:US530021
Vancouver, WA US         CITY:US530022
Charleston, WV US        CITY:US540003
Huntington, WV US        CITY:US540005
Morgantown, WV US        CITY:US540007
Parkersburg, WV US       CITY:US540008
Wheeling, WV US          CITY:US540009
Green Bay, WI US         CITY:US550002
Madison, WI US           CITY:US550006
Milwaukee, WI US         CITY:US550009
Casper, WY US            CITY:US560001
Cheyenne, WY US          CITY:US560002
Gillette, WY US          CITY:US560004
Laramie, WY US           CITY:US560005

[208 rows x 1 columns]

## Get data

In [55]:
df_index["id"]

name
Atlanta, GA US     CITY:US130004
New York, NY US    CITY:US360019
Name: id, dtype: object

In [77]:
CDD_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-CLDD-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid
    }
    response = requests.get(base_url, params=params,headers=headers)
    CDD = response.json()["results"][0]["value"]
    CDD_list.append(CDD)
df_index["CDD"] = CDD_list
df_index

                                    id   CDD
name
Birmingham, AL US        CITY:US010004  1933
Huntsville, AL US        CITY:US010012  1540
Mobile, AL US            CITY:US010014  2537
Montgomery, AL US        CITY:US010015  2113
Tuscaloosa, AL US        CITY:US010019  2348
Anchorage, AK US         CITY:US020001     3
Fairbanks, AK US         CITY:US020002    41
Juneau, AK US            CITY:US020003 -7777
Mesa, AZ US              CITY:US040008  3592
Phoenix, AZ US           CITY:US040011  3741
Tucson, AZ US            CITY:US040014  1946
Yuma, AZ US              CITY:US040015  3811
Conway, AR US            CITY:US050004  1843
Fayetteville, AR US      CITY:US050006  1517
Fort Smith, AR US        CITY:US050008  2053
Jonesboro, AR US         CITY:US050012  1735
Little Rock, AR US       CITY:US050013  2170
Los Angeles, CA US       CITY:US060013  1638
San Diego, CA US         CITY:US060030  1241
San Francisco, CA US     CITY:US060031   174
San Jose, CA US          CITY:US060032   395
Colorado Springs, CO US  CITY:US080003     6
Denver, CO US            CITY:US080004    15
Fort Collins, CO US      CITY:US080006   250
Pueblo, CO US            CITY:US080010  1092
Bridgeport, CT US        CITY:US090001   745
Hartford, CT US          CITY:US090003   603
New Haven, CT US         CITY:US090004   745
Stamford, CT US          CITY:US090008   799
Waterbury, CT US         CITY:US090010   754
...                                ...   ...
San Antonio, TX US       CITY:US480057  2364
Logan, UT US             CITY:US490003   704
Ogden, UT US             CITY:US490004  1174
Provo, UT US             CITY:US490005   662
Salt Lake City, UT US    CITY:US490006    21
St. George, UT US        CITY:US490007  2604
Burlington, VT US        CITY:US500001   484
Montpelier, VT US        CITY:US500002   453
Hampton, VA US           CITY:US510009  1836
Norfolk, VA US           CITY:US510014  1836
Richmond, VA US          CITY:US510015  1292
Roanoke, VA US           CITY:US510016  1061
Virginia Beach, VA US    CITY:US510017  1647
Everett, WA US           CITY:US530008   111
Seattle, WA US           CITY:US530018   165
Spokane, WA US           CITY:US530019   249
Tacoma, WA US            CITY:US530021   223
Vancouver, WA US         CITY:US530022   330
Charleston, WV US        CITY:US540003   924
Huntington, WV US        CITY:US540005   948
Morgantown, WV US        CITY:US540007   744
Parkersburg, WV US       CITY:US540008   894
Wheeling, WV US          CITY:US540009   909
Green Bay, WI US         CITY:US550002   358
Madison, WI US           CITY:US550006   597
Milwaukee, WI US         CITY:US550009   568
Casper, WY US            CITY:US560001   314
Cheyenne, WY US          CITY:US560002   364
Gillette, WY US          CITY:US560004   522
Laramie, WY US           CITY:US560005    70

[208 rows x 2 columns]

In [78]:
HDD_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-HTDD-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid
    }
    response = requests.get(base_url, params=params,headers=headers)
    HDD = response.json()["results"][0]["value"]
    HDD_list.append(HDD)
df_index["HDD"] = HDD_list
df_index

                                    id   CDD    HDD
name
Birmingham, AL US        CITY:US010004  1933   2770
Huntsville, AL US        CITY:US010012  1540   3517
Mobile, AL US            CITY:US010014  2537   1656
Montgomery, AL US        CITY:US010015  2113   2278
Tuscaloosa, AL US        CITY:US010019  2348   2338
Anchorage, AK US         CITY:US020001     3  10201
Fairbanks, AK US         CITY:US020002    41  13504
Juneau, AK US            CITY:US020003 -7777   9302
Mesa, AZ US              CITY:US040008  3592   1462
Phoenix, AZ US           CITY:US040011  3741   1359
Tucson, AZ US            CITY:US040014  1946   2486
Yuma, AZ US              CITY:US040015  3811   1129
Conway, AR US            CITY:US050004  1843   3472
Fayetteville, AR US      CITY:US050006  1517   4013
Fort Smith, AR US        CITY:US050008  2053   3244
Jonesboro, AR US         CITY:US050012  1735   3846
Little Rock, AR US       CITY:US050013  2170   3006
Los Angeles, CA US       CITY:US060013  1638    880
San Diego, CA US         CITY:US060030  1241   1909
San Francisco, CA US     CITY:US060031   174   2701
San Jose, CA US          CITY:US060032   395   2735
Colorado Springs, CO US  CITY:US080003     6   9474
Denver, CO US            CITY:US080004    15   8879
Fort Collins, CO US      CITY:US080006   250   7381
Pueblo, CO US            CITY:US080010  1092   5195
Bridgeport, CT US        CITY:US090001   745   5650
Hartford, CT US          CITY:US090003   603   6318
New Haven, CT US         CITY:US090004   745   5650
Stamford, CT US          CITY:US090008   799   5443
Waterbury, CT US         CITY:US090010   754   5678
...                                ...   ...    ...
San Antonio, TX US       CITY:US480057  2364   2049
Logan, UT US             CITY:US490003   704   6680
Ogden, UT US             CITY:US490004  1174   5670
Provo, UT US             CITY:US490005   662   5962
Salt Lake City, UT US    CITY:US490006    21   9639
St. George, UT US        CITY:US490007  2604   2986
Burlington, VT US        CITY:US500001   484   7432
Montpelier, VT US        CITY:US500002   453   7983
Hampton, VA US           CITY:US510009  1836   2958
Norfolk, VA US           CITY:US510014  1836   2958
Richmond, VA US          CITY:US510015  1292   4096
Roanoke, VA US           CITY:US510016  1061   4354
Virginia Beach, VA US    CITY:US510017  1647   3215
Everett, WA US           CITY:US530008   111   4937
Seattle, WA US           CITY:US530018   165   4919
Spokane, WA US           CITY:US530019   249   7139
Tacoma, WA US            CITY:US530021   223   4531
Vancouver, WA US         CITY:US530022   330   4447
Charleston, WV US        CITY:US540003   924   4955
Huntington, WV US        CITY:US540005   948   5223
Morgantown, WV US        CITY:US540007   744   5709
Parkersburg, WV US       CITY:US540008   894   5229
Wheeling, WV US          CITY:US540009   909   5303
Green Bay, WI US         CITY:US550002   358   7885
Madison, WI US           CITY:US550006   597   7283
Milwaukee, WI US         CITY:US550009   568   7304
Casper, WY US            CITY:US560001   314   7866
Cheyenne, WY US          CITY:US560002   364   7170
Gillette, WY US          CITY:US560004   522   7375
Laramie, WY US           CITY:US560005    70   8767

[208 rows x 3 columns]

In [79]:
Tavg_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-TAVG-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid,
        "units":"metric"
    }
    response = requests.get(base_url, params=params,headers=headers)
    Tavg = response.json()["results"][0]["value"]*9/5+32
    Tavg_list.append(Tavg)
df_index["Tavg"] = Tavg_list
df_index

                                    id   CDD    HDD   Tavg
name
Birmingham, AL US        CITY:US010004  1933   2770  62.78
Huntsville, AL US        CITY:US010012  1540   3517  59.54
Mobile, AL US            CITY:US010014  2537   1656  67.46
Montgomery, AL US        CITY:US010015  2113   2278  64.58
Tuscaloosa, AL US        CITY:US010019  2348   2338  64.94
Anchorage, AK US         CITY:US020001     3  10201  37.04
Fairbanks, AK US         CITY:US020002    41  13504  28.04
Juneau, AK US            CITY:US020003 -7777   9302  39.56
Mesa, AZ US              CITY:US040008  3592   1462  70.88
Phoenix, AZ US           CITY:US040011  3741   1359  71.42
Tucson, AZ US            CITY:US040014  1946   2486  63.50
Yuma, AZ US              CITY:US040015  3811   1129  72.32
Conway, AR US            CITY:US050004  1843   3472  60.44
Fayetteville, AR US      CITY:US050006  1517   4013  58.28
Fort Smith, AR US        CITY:US050008  2053   3244  61.70
Jonesboro, AR US         CITY:US050012  1735   3846  59.18
Little Rock, AR US       CITY:US050013  2170   3006  62.78
Los Angeles, CA US       CITY:US060013  1638    880  67.10
San Diego, CA US         CITY:US060030  1241   1909  63.14
San Francisco, CA US     CITY:US060031   174   2701  58.10
San Jose, CA US          CITY:US060032   395   2735  58.64
Colorado Springs, CO US  CITY:US080003     6   9474  39.02
Denver, CO US            CITY:US080004    15   8879  40.64
Fort Collins, CO US      CITY:US080006   250   7381  45.32
Pueblo, CO US            CITY:US080010  1092   5195  53.78
Bridgeport, CT US        CITY:US090001   745   5650  51.44
Hartford, CT US          CITY:US090003   603   6318  49.28
New Haven, CT US         CITY:US090004   745   5650  51.44
Stamford, CT US          CITY:US090008   799   5443  52.34
Waterbury, CT US         CITY:US090010   754   5678  51.44
...                                ...   ...    ...    ...
San Antonio, TX US       CITY:US480057  2364   2049  65.84
Logan, UT US             CITY:US490003   704   6680  48.56
Ogden, UT US             CITY:US490004  1174   5670  52.70
Provo, UT US             CITY:US490005   662   5962  50.54
Salt Lake City, UT US    CITY:US490006    21   9639  38.66
St. George, UT US        CITY:US490007  2604   2986  63.86
Burlington, VT US        CITY:US500001   484   7432  45.86
Montpelier, VT US        CITY:US500002   453   7983  44.42
Hampton, VA US           CITY:US510009  1836   2958  61.88
Norfolk, VA US           CITY:US510014  1836   2958  61.88
Richmond, VA US          CITY:US510015  1292   4096  57.38
Roanoke, VA US           CITY:US510016  1061   4354  55.94
Virginia Beach, VA US    CITY:US510017  1647   3215  60.62
Everett, WA US           CITY:US530008   111   4937  51.80
Seattle, WA US           CITY:US530018   165   4919  51.98
Spokane, WA US           CITY:US530019   249   7139  46.04
Tacoma, WA US            CITY:US530021   223   4531  53.24
Vancouver, WA US         CITY:US530022   330   4447  53.78
Charleston, WV US        CITY:US540003   924   4955  53.96
Huntington, WV US        CITY:US540005   948   5223  53.24
Morgantown, WV US        CITY:US540007   744   5709  51.44
Parkersburg, WV US       CITY:US540008   894   5229  53.06
Wheeling, WV US          CITY:US540009   909   5303  53.06
Green Bay, WI US         CITY:US550002   358   7885  44.42
Madison, WI US           CITY:US550006   597   7283  46.76
Milwaukee, WI US         CITY:US550009   568   7304  46.58
Casper, WY US            CITY:US560001   314   7866  44.24
Cheyenne, WY US          CITY:US560002   364   7170  46.22
Gillette, WY US          CITY:US560004   522   7375  46.22
Laramie, WY US           CITY:US560005    70   8767  41.18

[208 rows x 4 columns]

In [80]:
Trange_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-DUTR-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid,
        "units":"metric"
    }
    response = requests.get(base_url, params=params,headers=headers)
    Trange = response.json()["results"][0]["value"]*9/5+32
    Trange_list.append(Trange)
df_index["Trange"] = Trange_list
df_index

                                    id   CDD    HDD   Tavg  Trange
name
Birmingham, AL US        CITY:US010004  1933   2770  62.78   22.46
Huntsville, AL US        CITY:US010012  1540   3517  59.54   23.90
Mobile, AL US            CITY:US010014  2537   1656  67.46   18.68
Montgomery, AL US        CITY:US010015  2113   2278  64.58   23.54
Tuscaloosa, AL US        CITY:US010019  2348   2338  64.94   22.64
Anchorage, AK US         CITY:US020001     3  10201  37.04   14.00
Fairbanks, AK US         CITY:US020002    41  13504  28.04   21.02
Juneau, AK US            CITY:US020003 -7777   9302  39.56   10.94
Mesa, AZ US              CITY:US040008  3592   1462  70.88   27.68
Phoenix, AZ US           CITY:US040011  3741   1359  71.42   34.34
Tucson, AZ US            CITY:US040014  1946   2486  63.50   37.22
Yuma, AZ US              CITY:US040015  3811   1129  72.32   29.84
Conway, AR US            CITY:US050004  1843   3472  60.44   22.82
Fayetteville, AR US      CITY:US050006  1517   4013  58.28   20.84
Fort Smith, AR US        CITY:US050008  2053   3244  61.70   22.28
Jonesboro, AR US         CITY:US050012  1735   3846  59.18   21.92
Little Rock, AR US       CITY:US050013  2170   3006  62.78   18.68
Los Angeles, CA US       CITY:US060013  1638    880  67.10   22.64
San Diego, CA US         CITY:US060030  1241   1909  63.14   21.92
San Francisco, CA US     CITY:US060031   174   2701  58.10   19.40
San Jose, CA US          CITY:US060032   395   2735  58.64   30.20
Colorado Springs, CO US  CITY:US080003     6   9474  39.02   27.32
Denver, CO US            CITY:US080004    15   8879  40.64   31.64
Fort Collins, CO US      CITY:US080006   250   7381  45.32   22.64
Pueblo, CO US            CITY:US080010  1092   5195  53.78   30.56
Bridgeport, CT US        CITY:US090001   745   5650  51.44   18.86
Hartford, CT US          CITY:US090003   603   6318  49.28   21.92
New Haven, CT US         CITY:US090004   745   5650  51.44   18.86
Stamford, CT US          CITY:US090008   799   5443  52.34   21.92
Waterbury, CT US         CITY:US090010   754   5678  51.44   20.84
...                                ...   ...    ...    ...     ...
San Antonio, TX US       CITY:US480057  2364   2049  65.84   24.80
Logan, UT US             CITY:US490003   704   6680  48.56   21.74
Ogden, UT US             CITY:US490004  1174   5670  52.70   17.24
Provo, UT US             CITY:US490005   662   5962  50.54   24.62
Salt Lake City, UT US    CITY:US490006    21   9639  38.66   18.32
St. George, UT US        CITY:US490007  2604   2986  63.86   25.88
Burlington, VT US        CITY:US500001   484   7432  45.86   18.68
Montpelier, VT US        CITY:US500002   453   7983  44.42   24.62
Hampton, VA US           CITY:US510009  1836   2958  61.88   17.06
Norfolk, VA US           CITY:US510014  1836   2958  61.88   17.06
Richmond, VA US          CITY:US510015  1292   4096  57.38   20.66
Roanoke, VA US           CITY:US510016  1061   4354  55.94   23.54
Virginia Beach, VA US    CITY:US510017  1647   3215  60.62   16.52
Everett, WA US           CITY:US530008   111   4937  51.80   17.78
Seattle, WA US           CITY:US530018   165   4919  51.98   16.88
Spokane, WA US           CITY:US530019   249   7139  46.04   21.74
Tacoma, WA US            CITY:US530021   223   4531  53.24   17.24
Vancouver, WA US         CITY:US530022   330   4447  53.78   21.20
Charleston, WV US        CITY:US540003   924   4955  53.96   23.36
Huntington, WV US        CITY:US540005   948   5223  53.24   21.38
Morgantown, WV US        CITY:US540007   744   5709  51.44   22.46
Parkersburg, WV US       CITY:US540008   894   5229  53.06   21.74
Wheeling, WV US          CITY:US540009   909   5303  53.06   21.74
Green Bay, WI US         CITY:US550002   358   7885  44.42   18.50
Madison, WI US           CITY:US550006   597   7283  46.76   21.38
Milwaukee, WI US         CITY:US550009   568   7304  46.58   18.50
Casper, WY US            CITY:US560001   314   7866  44.24   25.88
Cheyenne, WY US          CITY:US560002   364   7170  46.22   30.92
Gillette, WY US          CITY:US560004   522   7375  46.22   26.06
Laramie, WY US           CITY:US560005    70   8767  41.18   29.12

[208 rows x 5 columns]

In [81]:
Tmax_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-TMAX-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid,
        "units":"metric"
    }
    response = requests.get(base_url, params=params,headers=headers)
    Tmax = response.json()["results"][0]["value"]*9/5+32
    Tmax_list.append(Tmax)
df_index["Tmax"] = Tmax_list
df_index

                                    id   CDD    HDD   Tavg  Trange   Tmax
name
Birmingham, AL US        CITY:US010004  1933   2770  62.78   22.46  73.94
Huntsville, AL US        CITY:US010012  1540   3517  59.54   23.90  71.42
Mobile, AL US            CITY:US010014  2537   1656  67.46   18.68  76.64
Montgomery, AL US        CITY:US010015  2113   2278  64.58   23.54  76.28
Tuscaloosa, AL US        CITY:US010019  2348   2338  64.94   22.64  76.28
Anchorage, AK US         CITY:US020001     3  10201  37.04   14.00  44.06
Fairbanks, AK US         CITY:US020002    41  13504  28.04   21.02  38.66
Juneau, AK US            CITY:US020003 -7777   9302  39.56   10.94  44.96
Mesa, AZ US              CITY:US040008  3592   1462  70.88   27.68  84.56
Phoenix, AZ US           CITY:US040011  3741   1359  71.42   34.34  88.70
Tucson, AZ US            CITY:US040014  1946   2486  63.50   37.22  82.04
Yuma, AZ US              CITY:US040015  3811   1129  72.32   29.84  87.26
Conway, AR US            CITY:US050004  1843   3472  60.44   22.82  71.96
Fayetteville, AR US      CITY:US050006  1517   4013  58.28   20.84  68.54
Fort Smith, AR US        CITY:US050008  2053   3244  61.70   22.28  72.86
Jonesboro, AR US         CITY:US050012  1735   3846  59.18   21.92  70.16
Little Rock, AR US       CITY:US050013  2170   3006  62.78   18.68  71.96
Los Angeles, CA US       CITY:US060013  1638    880  67.10   22.64  78.44
San Diego, CA US         CITY:US060030  1241   1909  63.14   21.92  74.12
San Francisco, CA US     CITY:US060031   174   2701  58.10   19.40  67.82
San Jose, CA US          CITY:US060032   395   2735  58.64   30.20  73.76
Colorado Springs, CO US  CITY:US080003     6   9474  39.02   27.32  52.88
Denver, CO US            CITY:US080004    15   8879  40.64   31.64  56.66
Fort Collins, CO US      CITY:US080006   250   7381  45.32   22.64  56.66
Pueblo, CO US            CITY:US080010  1092   5195  53.78   30.56  69.08
Bridgeport, CT US        CITY:US090001   745   5650  51.44   18.86  60.98
Hartford, CT US          CITY:US090003   603   6318  49.28   21.92  60.26
New Haven, CT US         CITY:US090004   745   5650  51.44   18.86  60.98
Stamford, CT US          CITY:US090008   799   5443  52.34   21.92  63.14
Waterbury, CT US         CITY:US090010   754   5678  51.44   20.84  61.88
...                                ...   ...    ...    ...     ...    ...
San Antonio, TX US       CITY:US480057  2364   2049  65.84   24.80  78.26
Logan, UT US             CITY:US490003   704   6680  48.56   21.74  59.54
Ogden, UT US             CITY:US490004  1174   5670  52.70   17.24  61.34
Provo, UT US             CITY:US490005   662   5962  50.54   24.62  62.78
Salt Lake City, UT US    CITY:US490006    21   9639  38.66   18.32  47.84
St. George, UT US        CITY:US490007  2604   2986  63.86   25.88  76.82
Burlington, VT US        CITY:US500001   484   7432  45.86   18.68  55.22
Montpelier, VT US        CITY:US500002   453   7983  44.42   24.62  56.66
Hampton, VA US           CITY:US510009  1836   2958  61.88   17.06  70.34
Norfolk, VA US           CITY:US510014  1836   2958  61.88   17.06  70.34
Richmond, VA US          CITY:US510015  1292   4096  57.38   20.66  67.64
Roanoke, VA US           CITY:US510016  1061   4354  55.94   23.54  67.64
Virginia Beach, VA US    CITY:US510017  1647   3215  60.62   16.52  69.08
Everett, WA US           CITY:US530008   111   4937  51.80   17.78  60.62
Seattle, WA US           CITY:US530018   165   4919  51.98   16.88  60.44
Spokane, WA US           CITY:US530019   249   7139  46.04   21.74  57.02
Tacoma, WA US            CITY:US530021   223   4531  53.24   17.24  61.88
Vancouver, WA US         CITY:US530022   330   4447  53.78   21.20  64.22
Charleston, WV US        CITY:US540003   924   4955  53.96   23.36  65.66
Huntington, WV US        CITY:US540005   948   5223  53.24   21.38  63.86
Morgantown, WV US        CITY:US540007   744   5709  51.44   22.46  62.60
Parkersburg, WV US       CITY:US540008   894   5229  53.06   21.74  64.04
Wheeling, WV US          CITY:US540009   909   5303  53.06   21.74  63.86
Green Bay, WI US         CITY:US550002   358   7885  44.42   18.50  53.60
Madison, WI US           CITY:US550006   597   7283  46.76   21.38  57.38
Milwaukee, WI US         CITY:US550009   568   7304  46.58   18.50  55.76
Casper, WY US            CITY:US560001   314   7866  44.24   25.88  57.20
Cheyenne, WY US          CITY:US560002   364   7170  46.22   30.92  61.88
Gillette, WY US          CITY:US560004   522   7375  46.22   26.06  59.18
Laramie, WY US           CITY:US560005    70   8767  41.18   29.12  55.76

[208 rows x 6 columns]

In [82]:
Tmin_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-TMIN-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid,
        "units":"metric"
    }
    response = requests.get(base_url, params=params,headers=headers)
    Tmin = response.json()["results"][0]["value"]*9/5+32
    Tmin_list.append(Tmin)
df_index["Tmin"] = Tmin_list
df_index

,id,CDD,HDD,Tavg,Trange,Tmax,Tmin
name,,,,,,,
"Birmingham, AL US",CITY:US010004,1933,2770,62.78,22.46,73.94,51.44
"Huntsville, AL US",CITY:US010012,1540,3517,59.54,23.90,71.42,47.66
"Mobile, AL US",CITY:US010014,2537,1656,67.46,18.68,76.64,58.10
"Montgomery, AL US",CITY:US010015,2113,2278,64.58,23.54,76.28,52.88
"Tuscaloosa, AL US",CITY:US010019,2348,2338,64.94,22.64,76.28,53.78
"Anchorage, AK US",CITY:US020001,3,10201,37.04,14.00,44.06,30.02
"Fairbanks, AK US",CITY:US020002,41,13504,28.04,21.02,38.66,17.60
"Juneau, AK US",CITY:US020003,-7777,9302,39.56,10.94,44.96,33.98
"Mesa, AZ US",CITY:US040008,3592,1462,70.88,27.68,84.56,57.02
"Phoenix, AZ US",CITY:US040011,3741,1359,71.42,34.34,88.70,54.32
"Tucson, AZ US",CITY:US040014,1946,2486,63.50,37.22,82.04,44.96
"Yuma, AZ US",CITY:US040015,3811,1129,72.32,29.84,87.26,57.38
"Conway, AR US",CITY:US050004,1843,3472,60.44,22.82,71.96,49.10
"Fayetteville, AR US",CITY:US050006,1517,4013,58.28,20.84,68.54,47.66
"Fort Smith, AR US",CITY:US050008,2053,3244,61.70,22.28,72.86,50.54
"Jonesboro, AR US",CITY:US050012,1735,3846,59.18,21.92,70.16,48.20
"Little Rock, AR US",CITY:US050013,2170,3006,62.78,18.68,71.96,53.24
"Los Angeles, CA US",CITY:US060013,1638,880,67.10,22.64,78.44,55.76
"San Diego, CA US",CITY:US060030,1241,1909,63.14,21.92,74.12,52.16
"San Francisco, CA US",CITY:US060031,174,2701,58.10,19.40,67.82,48.38
"San Jose, CA US",CITY:US060032,395,2735,58.64,30.20,73.76,43.52
"Colorado Springs, CO US",CITY:US080003,6,9474,39.02,27.32,52.88,25.34
"Denver, CO US",CITY:US080004,15,8879,40.64,31.64,56.66,24.80
"Fort Collins, CO US",CITY:US080006,250,7381,45.32,22.64,56.66,34.16
"Pueblo, CO US",CITY:US080010,1092,5195,53.78,30.56,69.08,38.48
"Bridgeport, CT US",CITY:US090001,745,5650,51.44,18.86,60.98,42.08
"Hartford, CT US",CITY:US090003,603,6318,49.28,21.92,60.26,38.48
"New Haven, CT US",CITY:US090004,745,5650,51.44,18.86,60.98,42.08
"Stamford, CT US",CITY:US090008,799,5443,52.34,21.92,63.14,41.36
"Waterbury, CT US",CITY:US090010,754,5678,51.44,20.84,61.88,41.00
...,...,...,...,...,...,...,...
"San Antonio, TX US",CITY:US480057,2364,2049,65.84,24.80,78.26,53.42
"Logan, UT US",CITY:US490003,704,6680,48.56,21.74,59.54,37.76
"Ogden, UT US",CITY:US490004,1174,5670,52.70,17.24,61.34,44.06
"Provo, UT US",CITY:US490005,662,5962,50.54,24.62,62.78,38.12
"Salt Lake City, UT US",CITY:US490006,21,9639,38.66,18.32,47.84,29.48
"St. George, UT US",CITY:US490007,2604,2986,63.86,25.88,76.82,51.08
"Burlington, VT US",CITY:US500001,484,7432,45.86,18.68,55.22,36.68
"Montpelier, VT US",CITY:US500002,453,7983,44.42,24.62,56.66,32.00
"Hampton, VA US",CITY:US510009,1836,2958,61.88,17.06,70.34,53.42
"Norfolk, VA US",CITY:US510014,1836,2958,61.88,17.06,70.34,53.42
"Richmond, VA US",CITY:US510015,1292,4096,57.38,20.66,67.64,46.94
"Roanoke, VA US",CITY:US510016,1061,4354,55.94,23.54,67.64,44.24
"Virginia Beach, VA US",CITY:US510017,1647,3215,60.62,16.52,69.08,52.34
"Everett, WA US",CITY:US530008,111,4937,51.80,17.78,60.62,42.98
"Seattle, WA US",CITY:US530018,165,4919,51.98,16.88,60.44,43.52
"Spokane, WA US",CITY:US530019,249,7139,46.04,21.74,57.02,35.24
"Tacoma, WA US",CITY:US530021,223,4531,53.24,17.24,61.88,44.60
"Vancouver, WA US",CITY:US530022,330,4447,53.78,21.20,64.22,43.16
"Charleston, WV US",CITY:US540003,924,4955,53.96,23.36,65.66,42.26
"Huntington, WV US",CITY:US540005,948,5223,53.24,21.38,63.86,42.62
"Morgantown, WV US",CITY:US540007,744,5709,51.44,22.46,62.60,40.28
"Parkersburg, WV US",CITY:US540008,894,5229,53.06,21.74,64.04,42.26
"Wheeling, WV US",CITY:US540009,909,5303,53.06,21.74,63.86,42.08
"Green Bay, WI US",CITY:US550002,358,7885,44.42,18.50,53.60,35.06
"Madison, WI US",CITY:US550006,597,7283,46.76,21.38,57.38,35.96
"Milwaukee, WI US",CITY:US550009,568,7304,46.58,18.50,55.76,37.22
"Casper, WY US",CITY:US560001,314,7866,44.24,25.88,57.20,31.46
"Cheyenne, WY US",CITY:US560002,364,7170,46.22,30.92,61.88,30.92
"Gillette, WY US",CITY:US560004,522,7375,46.22,26.06,59.18,33.26
"Laramie, WY US",CITY:US560005,70,8767,41.18,29.12,55.76,26.60

In [83]:
Prcp_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-PRCP-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid
    }
    response = requests.get(base_url, params=params,headers=headers)
    Prcp = response.json()["results"][0]["value"]
    Prcp_list.append(Prcp)
df_index["Prcp"] = Prcp_list
df_index

,id,CDD,HDD,Tavg,Trange,Tmax,Tmin,Prcp
name,,,,,,,,
"Birmingham, AL US",CITY:US010004,1933,2770,62.78,22.46,73.94,51.44,5712
"Huntsville, AL US",CITY:US010012,1540,3517,59.54,23.90,71.42,47.66,5582
"Mobile, AL US",CITY:US010014,2537,1656,67.46,18.68,76.64,58.10,6528
"Montgomery, AL US",CITY:US010015,2113,2278,64.58,23.54,76.28,52.88,5280
"Tuscaloosa, AL US",CITY:US010019,2348,2338,64.94,22.64,76.28,53.78,5046
"Anchorage, AK US",CITY:US020001,3,10201,37.04,14.00,44.06,30.02,1667
"Fairbanks, AK US",CITY:US020002,41,13504,28.04,21.02,38.66,17.60,1218
"Juneau, AK US",CITY:US020003,-7777,9302,39.56,10.94,44.96,33.98,11687
"Mesa, AZ US",CITY:US040008,3592,1462,70.88,27.68,84.56,57.02,943
"Phoenix, AZ US",CITY:US040011,3741,1359,71.42,34.34,88.70,54.32,876
"Tucson, AZ US",CITY:US040014,1946,2486,63.50,37.22,82.04,44.96,1390
"Yuma, AZ US",CITY:US040015,3811,1129,72.32,29.84,87.26,57.38,368
"Conway, AR US",CITY:US050004,1843,3472,60.44,22.82,71.96,49.10,4908
"Fayetteville, AR US",CITY:US050006,1517,4013,58.28,20.84,68.54,47.66,4553
"Fort Smith, AR US",CITY:US050008,2053,3244,61.70,22.28,72.86,50.54,5041
"Jonesboro, AR US",CITY:US050012,1735,3846,59.18,21.92,70.16,48.20,4823
"Little Rock, AR US",CITY:US050013,2170,3006,62.78,18.68,71.96,53.24,5468
"Los Angeles, CA US",CITY:US060013,1638,880,67.10,22.64,78.44,55.76,2297
"San Diego, CA US",CITY:US060030,1241,1909,63.14,21.92,74.12,52.16,1677
"San Francisco, CA US",CITY:US060031,174,2701,58.10,19.40,67.82,48.38,2674
"San Jose, CA US",CITY:US060032,395,2735,58.64,30.20,73.76,43.52,5048
"Colorado Springs, CO US",CITY:US080003,6,9474,39.02,27.32,52.88,25.34,1882
"Denver, CO US",CITY:US080004,15,8879,40.64,31.64,56.66,24.80,1773
"Fort Collins, CO US",CITY:US080006,250,7381,45.32,22.64,56.66,34.16,2162
"Pueblo, CO US",CITY:US080010,1092,5195,53.78,30.56,69.08,38.48,1302
"Bridgeport, CT US",CITY:US090001,745,5650,51.44,18.86,60.98,42.08,5110
"Hartford, CT US",CITY:US090003,603,6318,49.28,21.92,60.26,38.48,5344
"New Haven, CT US",CITY:US090004,745,5650,51.44,18.86,60.98,42.08,5110
"Stamford, CT US",CITY:US090008,799,5443,52.34,21.92,63.14,41.36,5004
"Waterbury, CT US",CITY:US090010,754,5678,51.44,20.84,61.88,41.00,5110
...,...,...,...,...,...,...,...,...
"San Antonio, TX US",CITY:US480057,2364,2049,65.84,24.80,78.26,53.42,3810
"Logan, UT US",CITY:US490003,704,6680,48.56,21.74,59.54,37.76,1776
"Ogden, UT US",CITY:US490004,1174,5670,52.70,17.24,61.34,44.06,1338
"Provo, UT US",CITY:US490005,662,5962,50.54,24.62,62.78,38.12,2053
"Salt Lake City, UT US",CITY:US490006,21,9639,38.66,18.32,47.84,29.48,5423
"St. George, UT US",CITY:US490007,2604,2986,63.86,25.88,76.82,51.08,1319
"Burlington, VT US",CITY:US500001,484,7432,45.86,18.68,55.22,36.68,3104
"Montpelier, VT US",CITY:US500002,453,7983,44.42,24.62,56.66,32.00,4242
"Hampton, VA US",CITY:US510009,1836,2958,61.88,17.06,70.34,53.42,5079
"Norfolk, VA US",CITY:US510014,1836,2958,61.88,17.06,70.34,53.42,5079
"Richmond, VA US",CITY:US510015,1292,4096,57.38,20.66,67.64,46.94,4341
"Roanoke, VA US",CITY:US510016,1061,4354,55.94,23.54,67.64,44.24,4711
"Virginia Beach, VA US",CITY:US510017,1647,3215,60.62,16.52,69.08,52.34,5079
"Everett, WA US",CITY:US530008,111,4937,51.80,17.78,60.62,42.98,3844
"Seattle, WA US",CITY:US530018,165,4919,51.98,16.88,60.44,43.52,5637
"Spokane, WA US",CITY:US530019,249,7139,46.04,21.74,57.02,35.24,1708
"Tacoma, WA US",CITY:US530021,223,4531,53.24,17.24,61.88,44.60,3914
"Vancouver, WA US",CITY:US530022,330,4447,53.78,21.20,64.22,43.16,4058
"Charleston, WV US",CITY:US540003,924,4955,53.96,23.36,65.66,42.26,4622
"Huntington, WV US",CITY:US540005,948,5223,53.24,21.38,63.86,42.62,4413
"Morgantown, WV US",CITY:US540007,744,5709,51.44,22.46,62.60,40.28,3958
"Parkersburg, WV US",CITY:US540008,894,5229,53.06,21.74,64.04,42.26,4106
"Wheeling, WV US",CITY:US540009,909,5303,53.06,21.74,63.86,42.08,4256
"Green Bay, WI US",CITY:US550002,358,7885,44.42,18.50,53.60,35.06,3127
"Madison, WI US",CITY:US550006,597,7283,46.76,21.38,57.38,35.96,3727
"Milwaukee, WI US",CITY:US550009,568,7304,46.58,18.50,55.76,37.22,3450
"Casper, WY US",CITY:US560001,314,7866,44.24,25.88,57.20,31.46,1301
"Cheyenne, WY US",CITY:US560002,364,7170,46.22,30.92,61.88,30.92,1727
"Gillette, WY US",CITY:US560004,522,7375,46.22,26.06,59.18,33.26,1694
"Laramie, WY US",CITY:US560005,70,8767,41.18,29.12,55.76,26.60,1143

In [84]:
Snow_list = []
for cityid in df_index["id"]:
    base_url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"
    params = {
        "datasetid":"NORMAL_ANN",
        "datatypeid":"ANN-SNOW-NORMAL",
        "startdate":"2010-01-01",
        "enddate":"2010-01-01",
        "locationid":cityid
    }
    response = requests.get(base_url, params=params,headers=headers)
    Snow = response.json()["results"][0]["value"]
    Snow_list.append(Snow)
df_index["Snow"] = Snow_list
df_index

,id,CDD,HDD,Tavg,Trange,Tmax,Tmin,Prcp,Snow
name,,,,,,,,,
"Birmingham, AL US",CITY:US010004,1933,2770,62.78,22.46,73.94,51.44,5712,8
"Huntsville, AL US",CITY:US010012,1540,3517,59.54,23.90,71.42,47.66,5582,24
"Mobile, AL US",CITY:US010014,2537,1656,67.46,18.68,76.64,58.10,6528,2
"Montgomery, AL US",CITY:US010015,2113,2278,64.58,23.54,76.28,52.88,5280,0
"Tuscaloosa, AL US",CITY:US010019,2348,2338,64.94,22.64,76.28,53.78,5046,2
"Anchorage, AK US",CITY:US020001,3,10201,37.04,14.00,44.06,30.02,1667,821
"Fairbanks, AK US",CITY:US020002,41,13504,28.04,21.02,38.66,17.60,1218,644
"Juneau, AK US",CITY:US020003,-7777,9302,39.56,10.94,44.96,33.98,11687,823
"Mesa, AZ US",CITY:US040008,3592,1462,70.88,27.68,84.56,57.02,943,0
"Phoenix, AZ US",CITY:US040011,3741,1359,71.42,34.34,88.70,54.32,876,0
"Tucson, AZ US",CITY:US040014,1946,2486,63.50,37.22,82.04,44.96,1390,23
"Yuma, AZ US",CITY:US040015,3811,1129,72.32,29.84,87.26,57.38,368,0
"Conway, AR US",CITY:US050004,1843,3472,60.44,22.82,71.96,49.10,4908,41
"Fayetteville, AR US",CITY:US050006,1517,4013,58.28,20.84,68.54,47.66,4553,43
"Fort Smith, AR US",CITY:US050008,2053,3244,61.70,22.28,72.86,50.54,5041,46
"Jonesboro, AR US",CITY:US050012,1735,3846,59.18,21.92,70.16,48.20,4823,48
"Little Rock, AR US",CITY:US050013,2170,3006,62.78,18.68,71.96,53.24,5468,44
"Los Angeles, CA US",CITY:US060013,1638,880,67.10,22.64,78.44,55.76,2297,0
"San Diego, CA US",CITY:US060030,1241,1909,63.14,21.92,74.12,52.16,1677,1
"San Francisco, CA US",CITY:US060031,174,2701,58.10,19.40,67.82,48.38,2674,0
"San Jose, CA US",CITY:US060032,395,2735,58.64,30.20,73.76,43.52,5048,1
"Colorado Springs, CO US",CITY:US080003,6,9474,39.02,27.32,52.88,25.34,1882,249
"Denver, CO US",CITY:US080004,15,8879,40.64,31.64,56.66,24.80,1773,857
"Fort Collins, CO US",CITY:US080006,250,7381,45.32,22.64,56.66,34.16,2162,1661
"Pueblo, CO US",CITY:US080010,1092,5195,53.78,30.56,69.08,38.48,1302,193
"Bridgeport, CT US",CITY:US090001,745,5650,51.44,18.86,60.98,42.08,5110,276
"Hartford, CT US",CITY:US090003,603,6318,49.28,21.92,60.26,38.48,5344,313
"New Haven, CT US",CITY:US090004,745,5650,51.44,18.86,60.98,42.08,5110,310
"Stamford, CT US",CITY:US090008,799,5443,52.34,21.92,63.14,41.36,5004,312
"Waterbury, CT US",CITY:US090010,754,5678,51.44,20.84,61.88,41.00,5110,310
...,...,...,...,...,...,...,...,...,...
"San Antonio, TX US",CITY:US480057,2364,2049,65.84,24.80,78.26,53.42,3810,-7777
"Logan, UT US",CITY:US490003,704,6680,48.56,21.74,59.54,37.76,1776,415
"Ogden, UT US",CITY:US490004,1174,5670,52.70,17.24,61.34,44.06,1338,485
"Provo, UT US",CITY:US490005,662,5962,50.54,24.62,62.78,38.12,2053,698
"Salt Lake City, UT US",CITY:US490006,21,9639,38.66,18.32,47.84,29.48,5423,5461
"St. George, UT US",CITY:US490007,2604,2986,63.86,25.88,76.82,51.08,1319,41
"Burlington, VT US",CITY:US500001,484,7432,45.86,18.68,55.22,36.68,3104,852
"Montpelier, VT US",CITY:US500002,453,7983,44.42,24.62,56.66,32.00,4242,805
"Hampton, VA US",CITY:US510009,1836,2958,61.88,17.06,70.34,53.42,5079,49
"Norfolk, VA US",CITY:US510014,1836,2958,61.88,17.06,70.34,53.42,5079,49
"Richmond, VA US",CITY:US510015,1292,4096,57.38,20.66,67.64,46.94,4341,165
"Roanoke, VA US",CITY:US510016,1061,4354,55.94,23.54,67.64,44.24,4711,213
"Virginia Beach, VA US",CITY:US510017,1647,3215,60.62,16.52,69.08,52.34,5079,58
"Everett, WA US",CITY:US530008,111,4937,51.80,17.78,60.62,42.98,3844,25
"Seattle, WA US",CITY:US530018,165,4919,51.98,16.88,60.44,43.52,5637,35
"Spokane, WA US",CITY:US530019,249,7139,46.04,21.74,57.02,35.24,1708,541
"Tacoma, WA US",CITY:US530021,223,4531,53.24,17.24,61.88,44.60,3914,48
"Vancouver, WA US",CITY:US530022,330,4447,53.78,21.20,64.22,43.16,4058,28
"Charleston, WV US",CITY:US540003,924,4955,53.96,23.36,65.66,42.26,4622,264
"Huntington, WV US",CITY:US540005,948,5223,53.24,21.38,63.86,42.62,4413,68
"Morgantown, WV US",CITY:US540007,744,5709,51.44,22.46,62.60,40.28,3958,378
"Parkersburg, WV US",CITY:US540008,894,5229,53.06,21.74,64.04,42.26,4106,119
"Wheeling, WV US",CITY:US540009,909,5303,53.06,21.74,63.86,42.08,4256,171
"Green Bay, WI US",CITY:US550002,358,7885,44.42,18.50,53.60,35.06,3127,514
"Madison, WI US",CITY:US550006,597,7283,46.76,21.38,57.38,35.96,3727,379
"Milwaukee, WI US",CITY:US550009,568,7304,46.58,18.50,55.76,37.22,3450,359
"Casper, WY US",CITY:US560001,314,7866,44.24,25.88,57.20,31.46,1301,734
"Cheyenne, WY US",CITY:US560002,364,7170,46.22,30.92,61.88,30.92,1727,512
"Gillette, WY US",CITY:US560004,522,7375,46.22,26.06,59.18,33.26,1694,588
"Laramie, WY US",CITY:US560005,70,8767,41.18,29.12,55.76,26.60,1143,497

In [1]:
df_index = df_index.reset_index()

NameError: name 'df_index' is not defined

In [85]:
df_index.to_csv("weather_data.csv")